/*
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * API version: v1
 * Contact: support@cloudsmith.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudsmith_api

type OrganizationGroupSync struct {
	// 
	IdpKey string `json:"idp_key"`
	// 
	IdpValue string `json:"idp_value"`
	//         User role within the team.          A `manager` is capable of adding/removing others to/from the team, and         can set the role of other users and other settings pertaining to the         team.          A 'member' is a normal user that inherits the settings and privileges         assigned to the team.         
	Role string `json:"role,omitempty"`
	// 
	SlugPerm string `json:"slug_perm,omitempty"`
	// 
	Team string `json:"team"`
}
