/*
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * API version: v1
 * Contact: support@cloudsmith.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudsmith_api

type OrganizationInvite struct {
	// 
	Email string `json:"email,omitempty"`
	// 
	ExpiresAt string `json:"expires_at,omitempty"`
	// 
	Inviter string `json:"inviter,omitempty"`
	// 
	InviterUrl string `json:"inviter_url,omitempty"`
	// 
	Org string `json:"org,omitempty"`
	// 
	Role string `json:"role,omitempty"`
	// 
	SlugPerm string `json:"slug_perm,omitempty"`
	// 
	User string `json:"user,omitempty"`
	// 
	UserUrl string `json:"user_url,omitempty"`
}
