/* 
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package cloudsmith_api

type PackagesUploadMaven struct {

	// The primary file for the package.
	PackageFile string `json:"package_file"`

	// Adds bundled Java source code to the Maven package.
	SourcesFile string `json:"sources_file,omitempty"`

	// Artifact's Maven packaging type.
	Packaging string `json:"packaging,omitempty"`

	// The POM file is an XML file containing the Maven coordinates.
	PomFile string `json:"pom_file,omitempty"`

	// Adds bundled Java documentation to the Maven package
	JavadocFile string `json:"javadoc_file,omitempty"`

	// The version of this package.
	Version string `json:"version,omitempty"`

	// Artifact's group ID.
	GroupId string `json:"group_id,omitempty"`

	// The ID of the artifact.
	ArtifactId string `json:"artifact_id,omitempty"`
}
