/* 
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package cloudsmith_api

type PackagesownerrepoFiles struct {

	// 
	CdnUrl string `json:"cdn_url,omitempty"`

	// 
	ChecksumMd5 string `json:"checksum_md5,omitempty"`

	// 
	ChecksumSha1 string `json:"checksum_sha1,omitempty"`

	// 
	ChecksumSha256 string `json:"checksum_sha256,omitempty"`

	// 
	ChecksumSha512 string `json:"checksum_sha512,omitempty"`

	// 
	Downloads int32 `json:"downloads,omitempty"`

	// 
	Filename string `json:"filename,omitempty"`

	// 
	IsDownloadable bool `json:"is_downloadable,omitempty"`

	// 
	IsPrimary bool `json:"is_primary,omitempty"`

	// 
	IsSynchronised bool `json:"is_synchronised,omitempty"`

	// 
	SignatureUrl string `json:"signature_url,omitempty"`

	// The calculated size of the file.
	Size int32 `json:"size,omitempty"`

	// 
	SlugPerm string `json:"slug_perm,omitempty"`

	// Freeform descriptor that describes what the file is.
	Tag string `json:"tag,omitempty"`
}
