/* 
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package cloudsmith_api

type PackagesownerrepoArchitectures struct {

	// 
	Description string `json:"description,omitempty"`

	// 
	Name string `json:"name,omitempty"`
}
