/* 
 * Cloudsmith API
 *
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package cloudsmith_api

type ResourcesRateCheck struct {

	// Rate limit values per resource
	Resources interface{} `json:"resources,omitempty"`
}
