# coding: utf-8

"""
    Cloudsmith API

    The API to the Cloudsmith Service

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudsmith_api
from cloudsmith_api.rest import ApiException
from cloudsmith_api.models.files_abort import FilesAbort


class TestFilesAbort(unittest.TestCase):
    """ FilesAbort unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesAbort(self):
        """
        Test FilesAbort
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudsmith_api.models.files_abort.FilesAbort()
        pass


if __name__ == '__main__':
    unittest.main()
