# coding: utf-8

"""
    Cloudsmith API

    The API to the Cloudsmith Service

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudsmith_api
from cloudsmith_api.rest import ApiException
from cloudsmith_api.models.packages_upload_helm import PackagesUploadHelm


class TestPackagesUploadHelm(unittest.TestCase):
    """ PackagesUploadHelm unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackagesUploadHelm(self):
        """
        Test PackagesUploadHelm
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudsmith_api.models.packages_upload_helm.PackagesUploadHelm()
        pass


if __name__ == '__main__':
    unittest.main()
