# coding: utf-8

"""
    Cloudsmith API (v1)

    The API to the Cloudsmith Service  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudsmith_api
from cloudsmith_api.models.repository_gpg_key_response import RepositoryGpgKeyResponse  # noqa: E501
from cloudsmith_api.rest import ApiException


class TestRepositoryGpgKeyResponse(unittest.TestCase):
    """RepositoryGpgKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryGpgKeyResponse(self):
        """Test RepositoryGpgKeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudsmith_api.models.repository_gpg_key_response.RepositoryGpgKeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
