# coding: utf-8

"""
    Cloudsmith API (v1)

    The API to the Cloudsmith Service  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cloudsmith_api.configuration import Configuration


class ConnectedRepository(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'disable_reason': 'str',
        'disable_reason_text': 'str',
        'is_active': 'bool',
        'priority': 'int',
        'slug_perm': 'str',
        'target_repository': 'str'
    }

    attribute_map = {
        'created_at': 'created_at',
        'disable_reason': 'disable_reason',
        'disable_reason_text': 'disable_reason_text',
        'is_active': 'is_active',
        'priority': 'priority',
        'slug_perm': 'slug_perm',
        'target_repository': 'target_repository'
    }

    def __init__(self, created_at=None, disable_reason='N/A', disable_reason_text=None, is_active=False, priority=None, slug_perm=None, target_repository=None, _configuration=None):  # noqa: E501
        """ConnectedRepository - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created_at = None
        self._disable_reason = None
        self._disable_reason_text = None
        self._is_active = None
        self._priority = None
        self._slug_perm = None
        self._target_repository = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if disable_reason is not None:
            self.disable_reason = disable_reason
        if disable_reason_text is not None:
            self.disable_reason_text = disable_reason_text
        if is_active is not None:
            self.is_active = is_active
        if priority is not None:
            self.priority = priority
        if slug_perm is not None:
            self.slug_perm = slug_perm
        self.target_repository = target_repository

    @property
    def created_at(self):
        """Gets the created_at of this ConnectedRepository.

        The date and time when the connection was created.

        :return: The created_at of this ConnectedRepository.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ConnectedRepository.

        The date and time when the connection was created.

        :param created_at: The created_at of this ConnectedRepository.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def disable_reason(self):
        """Gets the disable_reason of this ConnectedRepository.


        :return: The disable_reason of this ConnectedRepository.
        :rtype: str
        """
        return self._disable_reason

    @disable_reason.setter
    def disable_reason(self, disable_reason):
        """Sets the disable_reason of this ConnectedRepository.


        :param disable_reason: The disable_reason of this ConnectedRepository.
        :type: str
        """
        allowed_values = ["N/A", "The connection contains a circular reference"]  # noqa: E501
        if (self._configuration.client_side_validation and
                disable_reason not in allowed_values):
            raise ValueError(
                "Invalid value for `disable_reason` ({0}), must be one of {1}"  # noqa: E501
                .format(disable_reason, allowed_values)
            )

        self._disable_reason = disable_reason

    @property
    def disable_reason_text(self):
        """Gets the disable_reason_text of this ConnectedRepository.

        Human-readable explanation of why this connection is disabled.

        :return: The disable_reason_text of this ConnectedRepository.
        :rtype: str
        """
        return self._disable_reason_text

    @disable_reason_text.setter
    def disable_reason_text(self, disable_reason_text):
        """Sets the disable_reason_text of this ConnectedRepository.

        Human-readable explanation of why this connection is disabled.

        :param disable_reason_text: The disable_reason_text of this ConnectedRepository.
        :type: str
        """

        self._disable_reason_text = disable_reason_text

    @property
    def is_active(self):
        """Gets the is_active of this ConnectedRepository.


        :return: The is_active of this ConnectedRepository.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this ConnectedRepository.


        :param is_active: The is_active of this ConnectedRepository.
        :type: bool
        """

        self._is_active = is_active

    @property
    def priority(self):
        """Gets the priority of this ConnectedRepository.

        Repositories are checked in ascending order (starting at 1). If multiple repositories have the same priority, the oldest one is used first.

        :return: The priority of this ConnectedRepository.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this ConnectedRepository.

        Repositories are checked in ascending order (starting at 1). If multiple repositories have the same priority, the oldest one is used first.

        :param priority: The priority of this ConnectedRepository.
        :type: int
        """
        if (self._configuration.client_side_validation and
                priority is not None and priority > 32767):  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value less than or equal to `32767`")  # noqa: E501
        if (self._configuration.client_side_validation and
                priority is not None and priority < 1):  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value greater than or equal to `1`")  # noqa: E501

        self._priority = priority

    @property
    def slug_perm(self):
        """Gets the slug_perm of this ConnectedRepository.


        :return: The slug_perm of this ConnectedRepository.
        :rtype: str
        """
        return self._slug_perm

    @slug_perm.setter
    def slug_perm(self, slug_perm):
        """Sets the slug_perm of this ConnectedRepository.


        :param slug_perm: The slug_perm of this ConnectedRepository.
        :type: str
        """
        if (self._configuration.client_side_validation and
                slug_perm is not None and len(slug_perm) < 1):
            raise ValueError("Invalid value for `slug_perm`, length must be greater than or equal to `1`")  # noqa: E501
        if (self._configuration.client_side_validation and
                slug_perm is not None and not re.search('^[-a-zA-Z0-9_]+$', slug_perm)):  # noqa: E501
            raise ValueError(r"Invalid value for `slug_perm`, must be a follow pattern or equal to `/^[-a-zA-Z0-9_]+$/`")  # noqa: E501

        self._slug_perm = slug_perm

    @property
    def target_repository(self):
        """Gets the target_repository of this ConnectedRepository.

        The slug of the target repository to connect to.

        :return: The target_repository of this ConnectedRepository.
        :rtype: str
        """
        return self._target_repository

    @target_repository.setter
    def target_repository(self, target_repository):
        """Sets the target_repository of this ConnectedRepository.

        The slug of the target repository to connect to.

        :param target_repository: The target_repository of this ConnectedRepository.
        :type: str
        """
        if self._configuration.client_side_validation and target_repository is None:
            raise ValueError("Invalid value for `target_repository`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                target_repository is not None and not re.search('^[-a-zA-Z0-9_]+$', target_repository)):  # noqa: E501
            raise ValueError(r"Invalid value for `target_repository`, must be a follow pattern or equal to `/^[-a-zA-Z0-9_]+$/`")  # noqa: E501

        self._target_repository = target_repository

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectedRepository, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectedRepository):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConnectedRepository):
            return True

        return self.to_dict() != other.to_dict()

