# coding: utf-8

"""
    Cloudsmith API (v1)

    The API to the Cloudsmith Service  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cloudsmith_api.configuration import Configuration


class HistoryFieldsetRaw(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'downloaded': 'UsageRaw',
        'storage_used': 'StorageUsageRaw',
        'uploaded': 'UsageRaw'
    }

    attribute_map = {
        'downloaded': 'downloaded',
        'storage_used': 'storage_used',
        'uploaded': 'uploaded'
    }

    def __init__(self, downloaded=None, storage_used=None, uploaded=None, _configuration=None):  # noqa: E501
        """HistoryFieldsetRaw - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._downloaded = None
        self._storage_used = None
        self._uploaded = None
        self.discriminator = None

        self.downloaded = downloaded
        self.storage_used = storage_used
        self.uploaded = uploaded

    @property
    def downloaded(self):
        """Gets the downloaded of this HistoryFieldsetRaw.


        :return: The downloaded of this HistoryFieldsetRaw.
        :rtype: UsageRaw
        """
        return self._downloaded

    @downloaded.setter
    def downloaded(self, downloaded):
        """Sets the downloaded of this HistoryFieldsetRaw.


        :param downloaded: The downloaded of this HistoryFieldsetRaw.
        :type: UsageRaw
        """
        if self._configuration.client_side_validation and downloaded is None:
            raise ValueError("Invalid value for `downloaded`, must not be `None`")  # noqa: E501

        self._downloaded = downloaded

    @property
    def storage_used(self):
        """Gets the storage_used of this HistoryFieldsetRaw.


        :return: The storage_used of this HistoryFieldsetRaw.
        :rtype: StorageUsageRaw
        """
        return self._storage_used

    @storage_used.setter
    def storage_used(self, storage_used):
        """Sets the storage_used of this HistoryFieldsetRaw.


        :param storage_used: The storage_used of this HistoryFieldsetRaw.
        :type: StorageUsageRaw
        """
        if self._configuration.client_side_validation and storage_used is None:
            raise ValueError("Invalid value for `storage_used`, must not be `None`")  # noqa: E501

        self._storage_used = storage_used

    @property
    def uploaded(self):
        """Gets the uploaded of this HistoryFieldsetRaw.


        :return: The uploaded of this HistoryFieldsetRaw.
        :rtype: UsageRaw
        """
        return self._uploaded

    @uploaded.setter
    def uploaded(self, uploaded):
        """Sets the uploaded of this HistoryFieldsetRaw.


        :param uploaded: The uploaded of this HistoryFieldsetRaw.
        :type: UsageRaw
        """
        if self._configuration.client_side_validation and uploaded is None:
            raise ValueError("Invalid value for `uploaded`, must not be `None`")  # noqa: E501

        self._uploaded = uploaded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoryFieldsetRaw, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoryFieldsetRaw):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HistoryFieldsetRaw):
            return True

        return self.to_dict() != other.to_dict()

