# coding: utf-8

"""
    Cloudsmith API

    The API to the Cloudsmith Service

    OpenAPI spec version: v1
    Contact: support@cloudsmith.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MetricsownerrepopackagesusageActivePackages(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'slug': 'str',
        'version': 'str'
    }

    attribute_map = {
        'name': 'name',
        'slug': 'slug',
        'version': 'version'
    }

    def __init__(self, name=None, slug=None, version=None):
        """
        MetricsownerrepopackagesusageActivePackages - a model defined in Swagger
        """

        self._name = None
        self._slug = None
        self._version = None

        if name is not None:
          self.name = name
        if slug is not None:
          self.slug = slug
        if version is not None:
          self.version = version

    @property
    def name(self):
        """
        Gets the name of this MetricsownerrepopackagesusageActivePackages.
        

        :return: The name of this MetricsownerrepopackagesusageActivePackages.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this MetricsownerrepopackagesusageActivePackages.
        

        :param name: The name of this MetricsownerrepopackagesusageActivePackages.
        :type: str
        """

        self._name = name

    @property
    def slug(self):
        """
        Gets the slug of this MetricsownerrepopackagesusageActivePackages.
        

        :return: The slug of this MetricsownerrepopackagesusageActivePackages.
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """
        Sets the slug of this MetricsownerrepopackagesusageActivePackages.
        

        :param slug: The slug of this MetricsownerrepopackagesusageActivePackages.
        :type: str
        """

        self._slug = slug

    @property
    def version(self):
        """
        Gets the version of this MetricsownerrepopackagesusageActivePackages.
        

        :return: The version of this MetricsownerrepopackagesusageActivePackages.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this MetricsownerrepopackagesusageActivePackages.
        

        :param version: The version of this MetricsownerrepopackagesusageActivePackages.
        :type: str
        """

        self._version = version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MetricsownerrepopackagesusageActivePackages):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
