dist: trusty
sudo: false
language: java

cache:
 directories:
   - $HOME/.cache

jdk:
  - oraclejdk8

env:
  global:
    # CLOUDSMITH_API_KEY=foo
    - secure: O77shtv3KoeUGNCGXFgHMOapOFQKtop7Kzy73pw6/fctVKuv1+s/XbZchRvqPQ4Mbthu6UQh3Ij5HMRsftLH+YM8gLdmNejICPcUfM+z4GTt7UDEefCBvHXpWx1ktNJsgTUwNZwtrxb/k3oZ9GGewEw6Jw1dmrpRlBHsVwB1UX77kSEvGO+G11rr9Kz/hkx7owIewkuMxTTKmOa6drf38xNDklU1OW3GU9PROEd8LdChS0AxK+wSQAxSy+/w4a5qBILAoOh0gNwI4mv6+NTJVeC1E3kpML0YPbTxfvs2y7BXrYjW8jtDpQ5cNfbcDWZqoPvmT+rfQAioHsUl+fRq/39ASbllud7tuZYWTx+DYQhRpPHq7Kgj4/nrSGnL5kKvmr7YAEQlgiVkBcnPgOfwDzrjHx3fKpztWP5K1NkVvwLbdFDrUAccvKi7556dxOF3NCiIBgS4dIFmrGPVSiQIrhqfG6OigiJiIvyqmM8sboxDQK0jLFvdHN93ES27dY3Vpnra24vosdcDIdNR4YwPvZdeA019ymFhmUU/nhewXTzbjq6mstfFp2oaFL7R0fhcNLbWFOD85zKBl+we6dP1O4xrjjXO8AaqDfN2ZDyhCJUXGJ+lm3jK/iFfYZv+wNdbtW7sd9LkQtvVCk1BsK3j4kRUEOXaTtlJgzSS9m0H8ic=
    # PYPI_PASSWORD=foo
    - secure: UPnRJkkJzTY2ZD/dQRsMvRzq3auuAo+IKyNwd2eQqA02LfzyuPuS8ouQ/eEFawXJ9/WRoZHBTxR0Ww/eTnR+Vzyat6S6+22Aza6o37F1NJVRnV1oAioEtPpvMBxEoX87V5amFfDNlFyIFhhV9zkgcKC0aQkVybRS6H59x/0PniarhH9su6iJw+B/gVBWohLfaVoGIuTnaWYcvv7tU+TwekQsOI8IAMmqctukQCjROIQVZD9nSiYTq0sKYdHbbkEIeZW/yYCNxoc4lbuy2z/PDa3E5CQobT1fnmRCcZSk9N42TrCAtZFArdcZPelD1aiYOiWVncKptB4mHCvIvU/6+5IlGOJrlk7qCb4MozSnF83nrMjYTYwCOMExt6+Fj+e19U5c3XvrYenpyqXbCPBS2De/LO30zOyGRf+NAtDXvE5Sj3ttEtQhHR59XSNEzjDJrxftUFZW/+KhvoKooA8fxD5vWC4X3IbiUcuaCjAKQDtu5tmUzydvdAoDwc0+nY5BL+7DOBe3XMMPtulDvgdXmiidEtkm5eSAl6y7JeDN6SPISmm2gTJntkZgluSzQbpfQmkf+2zHuWaQyBXhzCfuBNrsEQIEl654QsTAelwYfz8ZrZfEiv/99a3RUoFNiQ/7BDx3K0equadM+Z/SmJED6fXqqyibtva5fhSyM3l7KR4=
    # RUBYGEMS_API_KEY=foo
    - secure: dXDr+hpOqgP3wyXrCquimxfFNZLAS491S6lkzdH0YJME+UTfC2vVPiVWgXgPsM7w5dpXsbxdPn4iXXBkSDJOoFjocBiCgYASmgQctX04ul8HmszddrpXPM9gF/lZdHqihui4IwM30DVsiScRdSrPAV3qcYifw0/ZGvqoRzUtL+mzqxwXyt5s5w5QJ5aTqbxwi8nALZLWb6vW4WY7+zvrz/8Jd8hhIj0/KWaF6dp52EsVXA1KIM/lWOLsCBJM/1GhbpMgQ+9ZFLEdema9CAR7mAge4vYzNOJ9bZZDicFLC+l2aJ8ioYFhRNIGS1LUSyDrm484aouOZ1xAOTX3S8lx1l0B+StneBPfNAlwfiVZh2Vz5k79CTrwOZ17a0+T6JwE2okTjgBdcnbBavy7k44wVc6OBgTK+iu3h5UNUF4hJOS2V9CnayfDdqR6mtX1aT/yuSqf6z4oijeV3rVT4KC7zwm4tBYzVZZ/DklK6cqH8z0cWci8a7obbjH5SJjGEDgRzI97uNeFGHCK3wE4d4T+krILd2bI/umY+0DnmVIMMxm+BA7QD9QulYCvqTZzr6x5svyU718KahSWM8p1W16N4aCURFBCx8S4oH6MrWUotI8brziNnSxCNBJtgx9LlKUJKt3I3M6rZIMCp0cz1kXmjLjArAp7zjPBuQbMyyGn5wc=

# TODO(ls): Put script into stages when it is supported:
# https://github.com/travis-ci/beta-features/issues/28
stages:
  - name: build
  - name: deploy
    if: branch = master AND type = push
    script:
      - ./scripts/deploy.sh $BINDING

jobs:
  include:
    - stage: build
      language: go
      go: 1.6
      env:
        BINDING=go
      deploy:
    - stage: build
      language: java
      jdk: oraclejdk8
      env:
        BINDING=java
    - stage: build
      language: python
      python: 2.7
      install:
        - pip install tox
      env:
        BINDING=python
    - stage: build
      language: ruby
      rvm: 2.2
      install:
        - gem install rake
      gemfile: bindings/ruby/src/Gemfile
      env:
        BINDING=ruby

script:
  - set -e
  - ./scripts/build.sh $BINDING
  - ./scripts/test.sh $BINDING
  - ./scripts/push.sh $BINDING

before_deploy:
  - pyenv global 2.7
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade wheel
  - pip install cloudsmith-cli twine

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh $BINDING
  on:
    branch: master

notifications:
  email:
    on_failure: always
    on_success: change
  slack:
    secure: qm4pgQYyTwTAkH0jTJxwMnvkWDhXEbulGRZUbMZbq2kvDAgnfWmusuvWNw0iGl9ArWpzgJxKKg1+hElKSuLgtTo4YGn78LoqhRTdZdNOSr+4/C8JRFeBZJMJUUqVzqWWdojuX5HogEjR6SmH+sr5KQkGJKaFanWNETQ8aaRSj1omt0dcLRoFQVNd2CXwo6qwRY/8r+a5sLBtOwSY/wtoTnBT6ebtNWctsyYmBClbJsUXlXlwRK7npDFz6S2f+6/0yiXoACz5XZLkwghMsX465rSMep9LVcFARAyZide2b+nkSqPdyFje4T7APhEWNCtXHg1AJSHw3KsQEXmnifJFdgRfTu8v7vM1dnBlTdXaRpavHJOVS0TEIvKdd5vmemNMPVVVMbTcQXwxSkl8oSacGjO8vbK91WGTJI3psoUKp7EP0MYeq9TAZpoZJHpemPg7H5fZdA5UyBFROaU7gsNb96JUDuGQAm+7AmrYx1YFqTjFioHtVF1XPs4elgkHEu1+D6kq9doKMQ+M38yIj1KkRtLjuEFKZ286joeoCrisPaFgsPsAHG46q1pqtIoXjQZKAwIvMbB1K7OuK5KO4oY+ppOZPZi56HLVh6oLzK4T6JA64JBIUo77dzOFO0hy/0riH6iEaOpG4hkt4f1sVBpGyTQxTpY/6Yzf8gQ2oJUvo3M=
