/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorDetail,
  VulnerabilityScanResults,
  VulnerabilityScanResultsList,
} from '../models/index';
import {
    ErrorDetailFromJSON,
    ErrorDetailToJSON,
    VulnerabilityScanResultsFromJSON,
    VulnerabilityScanResultsToJSON,
    VulnerabilityScanResultsListFromJSON,
    VulnerabilityScanResultsListToJSON,
} from '../models/index';

export interface VulnerabilitiesNamespaceListRequest {
    owner: string;
    page?: number;
    page_size?: number;
}

export interface VulnerabilitiesPackageListRequest {
    owner: string;
    repo: string;
    _package: string;
    page?: number;
    page_size?: number;
}

export interface VulnerabilitiesReadRequest {
    owner: string;
    repo: string;
    _package: string;
    identifier: string;
}

export interface VulnerabilitiesRepoListRequest {
    owner: string;
    repo: string;
    page?: number;
    page_size?: number;
}

/**
 * VulnerabilitiesApi - interface
 * 
 * @export
 * @interface VulnerabilitiesApiInterface
 */
export interface VulnerabilitiesApiInterface {
    /**
     * Lists scan results for a specific namespace.
     * @summary Lists scan results for a specific namespace.
     * @param {string} owner 
     * @param {number} [page] A page number within the paginated result set.
     * @param {number} [page_size] Number of results to return per page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VulnerabilitiesApiInterface
     */
    vulnerabilitiesNamespaceListRaw(requestParameters: VulnerabilitiesNamespaceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>>;

    /**
     * Lists scan results for a specific namespace.
     * Lists scan results for a specific namespace.
     */
    vulnerabilitiesNamespaceList(requestParameters: VulnerabilitiesNamespaceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>>;

    /**
     * Lists scan results for a specific package.
     * @summary Lists scan results for a specific package.
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} _package 
     * @param {number} [page] A page number within the paginated result set.
     * @param {number} [page_size] Number of results to return per page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VulnerabilitiesApiInterface
     */
    vulnerabilitiesPackageListRaw(requestParameters: VulnerabilitiesPackageListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>>;

    /**
     * Lists scan results for a specific package.
     * Lists scan results for a specific package.
     */
    vulnerabilitiesPackageList(requestParameters: VulnerabilitiesPackageListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>>;

    /**
     * Get a scan result.
     * @summary Get a scan result.
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} _package 
     * @param {string} identifier 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VulnerabilitiesApiInterface
     */
    vulnerabilitiesReadRaw(requestParameters: VulnerabilitiesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VulnerabilityScanResults>>;

    /**
     * Get a scan result.
     * Get a scan result.
     */
    vulnerabilitiesRead(requestParameters: VulnerabilitiesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VulnerabilityScanResults>;

    /**
     * Lists scan results for a specific repository.
     * @summary Lists scan results for a specific repository.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} [page] A page number within the paginated result set.
     * @param {number} [page_size] Number of results to return per page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VulnerabilitiesApiInterface
     */
    vulnerabilitiesRepoListRaw(requestParameters: VulnerabilitiesRepoListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>>;

    /**
     * Lists scan results for a specific repository.
     * Lists scan results for a specific repository.
     */
    vulnerabilitiesRepoList(requestParameters: VulnerabilitiesRepoListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>>;

}

/**
 * 
 */
export class VulnerabilitiesApi extends runtime.BaseAPI implements VulnerabilitiesApiInterface {

    /**
     * Lists scan results for a specific namespace.
     * Lists scan results for a specific namespace.
     */
    async vulnerabilitiesNamespaceListRaw(requestParameters: VulnerabilitiesNamespaceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling vulnerabilitiesNamespaceList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // apikey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/vulnerabilities/{owner}/`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VulnerabilityScanResultsListFromJSON));
    }

    /**
     * Lists scan results for a specific namespace.
     * Lists scan results for a specific namespace.
     */
    async vulnerabilitiesNamespaceList(requestParameters: VulnerabilitiesNamespaceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>> {
        const response = await this.vulnerabilitiesNamespaceListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists scan results for a specific package.
     * Lists scan results for a specific package.
     */
    async vulnerabilitiesPackageListRaw(requestParameters: VulnerabilitiesPackageListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling vulnerabilitiesPackageList().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling vulnerabilitiesPackageList().'
            );
        }

        if (requestParameters['_package'] == null) {
            throw new runtime.RequiredError(
                '_package',
                'Required parameter "_package" was null or undefined when calling vulnerabilitiesPackageList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // apikey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/vulnerabilities/{owner}/{repo}/{package}/`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"package"}}`, encodeURIComponent(String(requestParameters['_package']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VulnerabilityScanResultsListFromJSON));
    }

    /**
     * Lists scan results for a specific package.
     * Lists scan results for a specific package.
     */
    async vulnerabilitiesPackageList(requestParameters: VulnerabilitiesPackageListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>> {
        const response = await this.vulnerabilitiesPackageListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a scan result.
     * Get a scan result.
     */
    async vulnerabilitiesReadRaw(requestParameters: VulnerabilitiesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VulnerabilityScanResults>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling vulnerabilitiesRead().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling vulnerabilitiesRead().'
            );
        }

        if (requestParameters['_package'] == null) {
            throw new runtime.RequiredError(
                '_package',
                'Required parameter "_package" was null or undefined when calling vulnerabilitiesRead().'
            );
        }

        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling vulnerabilitiesRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // apikey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/vulnerabilities/{owner}/{repo}/{package}/{identifier}/`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"package"}}`, encodeURIComponent(String(requestParameters['_package']))).replace(`{${"identifier"}}`, encodeURIComponent(String(requestParameters['identifier']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VulnerabilityScanResultsFromJSON(jsonValue));
    }

    /**
     * Get a scan result.
     * Get a scan result.
     */
    async vulnerabilitiesRead(requestParameters: VulnerabilitiesReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VulnerabilityScanResults> {
        const response = await this.vulnerabilitiesReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists scan results for a specific repository.
     * Lists scan results for a specific repository.
     */
    async vulnerabilitiesRepoListRaw(requestParameters: VulnerabilitiesRepoListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VulnerabilityScanResultsList>>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling vulnerabilitiesRepoList().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling vulnerabilitiesRepoList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // apikey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/vulnerabilities/{owner}/{repo}/`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VulnerabilityScanResultsListFromJSON));
    }

    /**
     * Lists scan results for a specific repository.
     * Lists scan results for a specific repository.
     */
    async vulnerabilitiesRepoList(requestParameters: VulnerabilitiesRepoListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VulnerabilityScanResultsList>> {
        const response = await this.vulnerabilitiesRepoListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
