/*
 * Cloudsmith API
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.apis;

import io.cloudsmith.api.models.Quota;
import io.cloudsmith.api.models.QuotaHistory;
import io.cloudsmith.api.models.Status;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuotaApi
 */
@Ignore
public class QuotaApiTest {

    private final QuotaApi api = new QuotaApi();

    
    /**
     * Quota history for a given namespace.
     *
     * Quota history for a given namespace.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void quotaHistoryReadTest() throws Exception {
        String owner = null;
        QuotaHistory response = api.quotaHistoryRead(owner);

        // TODO: test validations
    }
    
    /**
     * Open-source Quota history for a given namespace.
     *
     * Open-source Quota history for a given namespace.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void quotaOssHistoryReadTest() throws Exception {
        String owner = null;
        QuotaHistory response = api.quotaOssHistoryRead(owner);

        // TODO: test validations
    }
    
    /**
     * Open-source Quota usage for a given namespace.
     *
     * Open-source Quota usage for a given namespace.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void quotaOssReadTest() throws Exception {
        String owner = null;
        Quota response = api.quotaOssRead(owner);

        // TODO: test validations
    }
    
    /**
     * Quota usage for a given namespace.
     *
     * Quota usage for a given namespace.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void quotaReadTest() throws Exception {
        String owner = null;
        Quota response = api.quotaRead(owner);

        // TODO: test validations
    }
    
}
