/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ConnectedRepository
 */

public class ConnectedRepository implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  /**
   * Gets or Sets disableReason
   */
  @JsonAdapter(DisableReasonEnum.Adapter.class)
  public enum DisableReasonEnum {
    N_A("N/A"),
    
    THE_CONNECTION_CONTAINS_A_CIRCULAR_REFERENCE("The connection contains a circular reference");

    private String value;

    DisableReasonEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DisableReasonEnum fromValue(String text) {
      for (DisableReasonEnum b : DisableReasonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DisableReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DisableReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DisableReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DisableReasonEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("disable_reason")
  private DisableReasonEnum disableReason = DisableReasonEnum.N_A;

  @SerializedName("disable_reason_text")
  private String disableReasonText = null;

  @SerializedName("is_active")
  private Boolean isActive = false;

  @SerializedName("priority")
  private java.math.BigInteger priority = null;

  @SerializedName("slug_perm")
  private String slugPerm = null;

  @SerializedName("target_repository")
  private String targetRepository = null;

   /**
   * The date and time when the connection was created.
   * @return createdAt
  **/
  @Valid
  @ApiModelProperty(value = "The date and time when the connection was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

   /**
   * Get disableReason
   * @return disableReason
  **/
  @ApiModelProperty(value = "")
  public DisableReasonEnum getDisableReason() {
    return disableReason;
  }

   /**
   * Human-readable explanation of why this connection is disabled.
   * @return disableReasonText
  **/
  @ApiModelProperty(value = "Human-readable explanation of why this connection is disabled.")
  public String getDisableReasonText() {
    return disableReasonText;
  }

  public ConnectedRepository isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public ConnectedRepository priority(java.math.BigInteger priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Repositories are checked in ascending order (starting at 1). If multiple repositories have the same priority, the oldest one is used first.
   * minimum: 1
   * maximum: 32767
   * @return priority
  **/
 @Min(1L) @Max(32767L)  @ApiModelProperty(value = "Repositories are checked in ascending order (starting at 1). If multiple repositories have the same priority, the oldest one is used first.")
  public java.math.BigInteger getPriority() {
    return priority;
  }

  public void setPriority(java.math.BigInteger priority) {
    this.priority = priority;
  }

   /**
   * Get slugPerm
   * @return slugPerm
  **/
 @Pattern(regexp="^[-a-zA-Z0-9_]+$") @Size(min=1)  @ApiModelProperty(value = "")
  public String getSlugPerm() {
    return slugPerm;
  }

  public ConnectedRepository targetRepository(String targetRepository) {
    this.targetRepository = targetRepository;
    return this;
  }

   /**
   * The slug of the target repository to connect to.
   * @return targetRepository
  **/
  @NotNull
 @Pattern(regexp="^[-a-zA-Z0-9_]+$")  @ApiModelProperty(required = true, value = "The slug of the target repository to connect to.")
  public String getTargetRepository() {
    return targetRepository;
  }

  public void setTargetRepository(String targetRepository) {
    this.targetRepository = targetRepository;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectedRepository connectedRepository = (ConnectedRepository) o;
    return Objects.equals(this.createdAt, connectedRepository.createdAt) &&
        Objects.equals(this.disableReason, connectedRepository.disableReason) &&
        Objects.equals(this.disableReasonText, connectedRepository.disableReasonText) &&
        Objects.equals(this.isActive, connectedRepository.isActive) &&
        Objects.equals(this.priority, connectedRepository.priority) &&
        Objects.equals(this.slugPerm, connectedRepository.slugPerm) &&
        Objects.equals(this.targetRepository, connectedRepository.targetRepository);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, disableReason, disableReasonText, isActive, priority, slugPerm, targetRepository);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectedRepository {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    disableReason: ").append(toIndentedString(disableReason)).append("\n");
    sb.append("    disableReasonText: ").append(toIndentedString(disableReasonText)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    slugPerm: ").append(toIndentedString(slugPerm)).append("\n");
    sb.append("    targetRepository: ").append(toIndentedString(targetRepository)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

