/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.cloudsmith.api.models.WebOSVSeverityCounts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GenericPackageUploadRequest
 */

public class GenericPackageUploadRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("filepath")
  private String filepath = null;

  @SerializedName("is_malware_detected")
  private Boolean isMalwareDetected = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("package_file")
  private String packageFile = null;

  @SerializedName("republish")
  private Boolean republish = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("vulnerability_counts")
  private WebOSVSeverityCounts vulnerabilityCounts = null;

  public GenericPackageUploadRequest filepath(String filepath) {
    this.filepath = filepath;
    return this;
  }

   /**
   * The full filepath of the package including filename.
   * @return filepath
  **/
  @NotNull
 @Size(min=1,max=2083)  @ApiModelProperty(required = true, value = "The full filepath of the package including filename.")
  public String getFilepath() {
    return filepath;
  }

  public void setFilepath(String filepath) {
    this.filepath = filepath;
  }

   /**
   * Whether the package has been detected as containing malware. Requires Ultra plan.
   * @return isMalwareDetected
  **/
  @ApiModelProperty(value = "Whether the package has been detected as containing malware. Requires Ultra plan.")
  public Boolean isIsMalwareDetected() {
    return isMalwareDetected;
  }

  public GenericPackageUploadRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this package.
   * @return name
  **/
 @Size(max=200)  @ApiModelProperty(value = "The name of this package.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GenericPackageUploadRequest packageFile(String packageFile) {
    this.packageFile = packageFile;
    return this;
  }

   /**
   * The primary file for the package.
   * @return packageFile
  **/
  @NotNull
 @Size(min=1)  @ApiModelProperty(required = true, value = "The primary file for the package.")
  public String getPackageFile() {
    return packageFile;
  }

  public void setPackageFile(String packageFile) {
    this.packageFile = packageFile;
  }

  public GenericPackageUploadRequest republish(Boolean republish) {
    this.republish = republish;
    return this;
  }

   /**
   * If true, the uploaded package will overwrite any others with the same attributes (e.g. same version); otherwise, it will be flagged as a duplicate.
   * @return republish
  **/
  @ApiModelProperty(value = "If true, the uploaded package will overwrite any others with the same attributes (e.g. same version); otherwise, it will be flagged as a duplicate.")
  public Boolean isRepublish() {
    return republish;
  }

  public void setRepublish(Boolean republish) {
    this.republish = republish;
  }

  public GenericPackageUploadRequest tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * A comma-separated values list of tags to add to the package.
   * @return tags
  **/
 @Size(min=1,max=1024)  @ApiModelProperty(value = "A comma-separated values list of tags to add to the package.")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public GenericPackageUploadRequest version(String version) {
    this.version = version;
    return this;
  }

   /**
   * The raw version for this package.
   * @return version
  **/
 @Size(max=255)  @ApiModelProperty(value = "The raw version for this package.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public GenericPackageUploadRequest vulnerabilityCounts(WebOSVSeverityCounts vulnerabilityCounts) {
    this.vulnerabilityCounts = vulnerabilityCounts;
    return this;
  }

   /**
   * Get vulnerabilityCounts
   * @return vulnerabilityCounts
  **/
  @Valid
  @ApiModelProperty(value = "")
  public WebOSVSeverityCounts getVulnerabilityCounts() {
    return vulnerabilityCounts;
  }

  public void setVulnerabilityCounts(WebOSVSeverityCounts vulnerabilityCounts) {
    this.vulnerabilityCounts = vulnerabilityCounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericPackageUploadRequest genericPackageUploadRequest = (GenericPackageUploadRequest) o;
    return Objects.equals(this.filepath, genericPackageUploadRequest.filepath) &&
        Objects.equals(this.isMalwareDetected, genericPackageUploadRequest.isMalwareDetected) &&
        Objects.equals(this.name, genericPackageUploadRequest.name) &&
        Objects.equals(this.packageFile, genericPackageUploadRequest.packageFile) &&
        Objects.equals(this.republish, genericPackageUploadRequest.republish) &&
        Objects.equals(this.tags, genericPackageUploadRequest.tags) &&
        Objects.equals(this.version, genericPackageUploadRequest.version) &&
        Objects.equals(this.vulnerabilityCounts, genericPackageUploadRequest.vulnerabilityCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filepath, isMalwareDetected, name, packageFile, republish, tags, version, vulnerabilityCounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericPackageUploadRequest {\n");
    
    sb.append("    filepath: ").append(toIndentedString(filepath)).append("\n");
    sb.append("    isMalwareDetected: ").append(toIndentedString(isMalwareDetected)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    packageFile: ").append(toIndentedString(packageFile)).append("\n");
    sb.append("    republish: ").append(toIndentedString(republish)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    vulnerabilityCounts: ").append(toIndentedString(vulnerabilityCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

