/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * InlineResponse2001
 */

public class InlineResponse2001 implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("allow_open_source_overage")
  private Boolean allowOpenSourceOverage = null;

  @SerializedName("bandwidth_overage_limit")
  private java.math.BigInteger bandwidthOverageLimit = null;

  @SerializedName("storage_overage_limit")
  private java.math.BigInteger storageOverageLimit = null;

  public InlineResponse2001 allowOpenSourceOverage(Boolean allowOpenSourceOverage) {
    this.allowOpenSourceOverage = allowOpenSourceOverage;
    return this;
  }

   /**
   * Whether on-demand open source overage is allowed.
   * @return allowOpenSourceOverage
  **/
  @ApiModelProperty(value = "Whether on-demand open source overage is allowed.")
  public Boolean isAllowOpenSourceOverage() {
    return allowOpenSourceOverage;
  }

  public void setAllowOpenSourceOverage(Boolean allowOpenSourceOverage) {
    this.allowOpenSourceOverage = allowOpenSourceOverage;
  }

  public InlineResponse2001 bandwidthOverageLimit(java.math.BigInteger bandwidthOverageLimit) {
    this.bandwidthOverageLimit = bandwidthOverageLimit;
    return this;
  }

   /**
   * Effective bandwidth overage limit in GB.
   * @return bandwidthOverageLimit
  **/
  @ApiModelProperty(value = "Effective bandwidth overage limit in GB.")
  public java.math.BigInteger getBandwidthOverageLimit() {
    return bandwidthOverageLimit;
  }

  public void setBandwidthOverageLimit(java.math.BigInteger bandwidthOverageLimit) {
    this.bandwidthOverageLimit = bandwidthOverageLimit;
  }

  public InlineResponse2001 storageOverageLimit(java.math.BigInteger storageOverageLimit) {
    this.storageOverageLimit = storageOverageLimit;
    return this;
  }

   /**
   * Effective storage overage limit in GB.
   * @return storageOverageLimit
  **/
  @ApiModelProperty(value = "Effective storage overage limit in GB.")
  public java.math.BigInteger getStorageOverageLimit() {
    return storageOverageLimit;
  }

  public void setStorageOverageLimit(java.math.BigInteger storageOverageLimit) {
    this.storageOverageLimit = storageOverageLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.allowOpenSourceOverage, inlineResponse2001.allowOpenSourceOverage) &&
        Objects.equals(this.bandwidthOverageLimit, inlineResponse2001.bandwidthOverageLimit) &&
        Objects.equals(this.storageOverageLimit, inlineResponse2001.storageOverageLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowOpenSourceOverage, bandwidthOverageLimit, storageOverageLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    allowOpenSourceOverage: ").append(toIndentedString(allowOpenSourceOverage)).append("\n");
    sb.append("    bandwidthOverageLimit: ").append(toIndentedString(bandwidthOverageLimit)).append("\n");
    sb.append("    storageOverageLimit: ").append(toIndentedString(storageOverageLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

