/*
 * Cloudsmith API
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * PackagesValidateuploadNuget
 */

public class PackagesValidateuploadNuget implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("package_file")
  private String packageFile = null;

  @SerializedName("republish")
  private Boolean republish = null;

  @SerializedName("symbols_file")
  private String symbolsFile = null;

  @SerializedName("tags")
  private String tags = null;

  public PackagesValidateuploadNuget packageFile(String packageFile) {
    this.packageFile = packageFile;
    return this;
  }

   /**
   * The primary file for the package.
   * @return packageFile
  **/
  @NotNull
  @ApiModelProperty(example = "y1234456789a", required = true, value = "The primary file for the package.")
  public String getPackageFile() {
    return packageFile;
  }

  public void setPackageFile(String packageFile) {
    this.packageFile = packageFile;
  }

  public PackagesValidateuploadNuget republish(Boolean republish) {
    this.republish = republish;
    return this;
  }

   /**
   * If true, the uploaded package will overwrite any others with the same attributes (e.g. same version); otherwise, it will be flagged as a duplicate.
   * @return republish
  **/
  @ApiModelProperty(value = "If true, the uploaded package will overwrite any others with the same attributes (e.g. same version); otherwise, it will be flagged as a duplicate.")
  public Boolean getRepublish() {
    return republish;
  }

  public void setRepublish(Boolean republish) {
    this.republish = republish;
  }

  public PackagesValidateuploadNuget symbolsFile(String symbolsFile) {
    this.symbolsFile = symbolsFile;
    return this;
  }

   /**
   * Attaches a symbols file to the package.
   * @return symbolsFile
  **/
  @ApiModelProperty(example = "y1234456789b", value = "Attaches a symbols file to the package.")
  public String getSymbolsFile() {
    return symbolsFile;
  }

  public void setSymbolsFile(String symbolsFile) {
    this.symbolsFile = symbolsFile;
  }

  public PackagesValidateuploadNuget tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * A comma-separated values list of tags to add to the package.
   * @return tags
  **/
  @ApiModelProperty(value = "A comma-separated values list of tags to add to the package.")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackagesValidateuploadNuget packagesValidateuploadNuget = (PackagesValidateuploadNuget) o;
    return Objects.equals(this.packageFile, packagesValidateuploadNuget.packageFile) &&
        Objects.equals(this.republish, packagesValidateuploadNuget.republish) &&
        Objects.equals(this.symbolsFile, packagesValidateuploadNuget.symbolsFile) &&
        Objects.equals(this.tags, packagesValidateuploadNuget.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageFile, republish, symbolsFile, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackagesValidateuploadNuget {\n");
    
    sb.append("    packageFile: ").append(toIndentedString(packageFile)).append("\n");
    sb.append("    republish: ").append(toIndentedString(republish)).append("\n");
    sb.append("    symbolsFile: ").append(toIndentedString(symbolsFile)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

