/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.cloudsmith.api.models.DynamicMapping;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ProviderSettingsWriteRequest
 */

public class ProviderSettingsWriteRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("claims")
  private Object claims = null;

  @SerializedName("dynamic_mappings")
  private List<DynamicMapping> dynamicMappings = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("mapping_claim")
  private String mappingClaim = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("provider_url")
  private String providerUrl = null;

  @SerializedName("service_accounts")
  private List<String> serviceAccounts = null;

  public ProviderSettingsWriteRequest claims(Object claims) {
    this.claims = claims;
    return this;
  }

   /**
   * The set of claims that any received tokens from the provider must contain to authenticate as the configured service account.
   * @return claims
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "The set of claims that any received tokens from the provider must contain to authenticate as the configured service account.")
  public Object getClaims() {
    return claims;
  }

  public void setClaims(Object claims) {
    this.claims = claims;
  }

  public ProviderSettingsWriteRequest dynamicMappings(List<DynamicMapping> dynamicMappings) {
    this.dynamicMappings = dynamicMappings;
    return this;
  }

  public ProviderSettingsWriteRequest addDynamicMappingsItem(DynamicMapping dynamicMappingsItem) {
    if (this.dynamicMappings == null) {
      this.dynamicMappings = new ArrayList<>();
    }
    this.dynamicMappings.add(dynamicMappingsItem);
    return this;
  }

   /**
   * The dynamic mappings of &#x60;mapping_claim&#x60; values to service accounts. Cannot be provided if &#x60;service_accounts&#x60; is also set.  Note: This field and the dynamic mappings feature are still in early access. Breaking changes are possible as we receive feedback on this feature.
   * @return dynamicMappings
  **/
  @Valid
  @ApiModelProperty(value = "The dynamic mappings of `mapping_claim` values to service accounts. Cannot be provided if `service_accounts` is also set.  Note: This field and the dynamic mappings feature are still in early access. Breaking changes are possible as we receive feedback on this feature.")
  public List<DynamicMapping> getDynamicMappings() {
    return dynamicMappings;
  }

  public void setDynamicMappings(List<DynamicMapping> dynamicMappings) {
    this.dynamicMappings = dynamicMappings;
  }

  public ProviderSettingsWriteRequest enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether the provider settings should be used for incoming OIDC requests.
   * @return enabled
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Whether the provider settings should be used for incoming OIDC requests.")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ProviderSettingsWriteRequest mappingClaim(String mappingClaim) {
    this.mappingClaim = mappingClaim;
    return this;
  }

   /**
   * The OIDC claim to use for mapping to service accounts in dynamic_mappings. Cannot be provided if &#x60;service_accounts&#x60; is also set.  Note: This field and the dynamic mappings feature are still in early access. Breaking changes are possible as we receive feedback on this feature.
   * @return mappingClaim
  **/
 @Size(min=1)  @ApiModelProperty(value = "The OIDC claim to use for mapping to service accounts in dynamic_mappings. Cannot be provided if `service_accounts` is also set.  Note: This field and the dynamic mappings feature are still in early access. Breaking changes are possible as we receive feedback on this feature.")
  public String getMappingClaim() {
    return mappingClaim;
  }

  public void setMappingClaim(String mappingClaim) {
    this.mappingClaim = mappingClaim;
  }

  public ProviderSettingsWriteRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the provider settings are being configured for
   * @return name
  **/
  @NotNull
 @Size(min=1)  @ApiModelProperty(required = true, value = "The name of the provider settings are being configured for")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProviderSettingsWriteRequest providerUrl(String providerUrl) {
    this.providerUrl = providerUrl;
    return this;
  }

   /**
   * The URL from the provider that serves as the base for the OpenID configuration. For example, if the OpenID configuration is available at https://token.actions.githubusercontent.com/.well-known/openid-configuration, the provider URL would be https://token.actions.githubusercontent.com/
   * @return providerUrl
  **/
  @NotNull
 @Size(min=1)  @ApiModelProperty(required = true, value = "The URL from the provider that serves as the base for the OpenID configuration. For example, if the OpenID configuration is available at https://token.actions.githubusercontent.com/.well-known/openid-configuration, the provider URL would be https://token.actions.githubusercontent.com/")
  public String getProviderUrl() {
    return providerUrl;
  }

  public void setProviderUrl(String providerUrl) {
    this.providerUrl = providerUrl;
  }

  public ProviderSettingsWriteRequest serviceAccounts(List<String> serviceAccounts) {
    this.serviceAccounts = serviceAccounts;
    return this;
  }

  public ProviderSettingsWriteRequest addServiceAccountsItem(String serviceAccountsItem) {
    if (this.serviceAccounts == null) {
      this.serviceAccounts = new ArrayList<>();
    }
    this.serviceAccounts.add(serviceAccountsItem);
    return this;
  }

   /**
   * The service accounts associated with these provider settings. Cannot be provided if &#x60;mapping_claim&#x60; or &#x60;dynamic_mappings&#x60; are specified.
   * @return serviceAccounts
  **/
  @ApiModelProperty(value = "The service accounts associated with these provider settings. Cannot be provided if `mapping_claim` or `dynamic_mappings` are specified.")
  public List<String> getServiceAccounts() {
    return serviceAccounts;
  }

  public void setServiceAccounts(List<String> serviceAccounts) {
    this.serviceAccounts = serviceAccounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderSettingsWriteRequest providerSettingsWriteRequest = (ProviderSettingsWriteRequest) o;
    return Objects.equals(this.claims, providerSettingsWriteRequest.claims) &&
        Objects.equals(this.dynamicMappings, providerSettingsWriteRequest.dynamicMappings) &&
        Objects.equals(this.enabled, providerSettingsWriteRequest.enabled) &&
        Objects.equals(this.mappingClaim, providerSettingsWriteRequest.mappingClaim) &&
        Objects.equals(this.name, providerSettingsWriteRequest.name) &&
        Objects.equals(this.providerUrl, providerSettingsWriteRequest.providerUrl) &&
        Objects.equals(this.serviceAccounts, providerSettingsWriteRequest.serviceAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claims, dynamicMappings, enabled, mappingClaim, name, providerUrl, serviceAccounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderSettingsWriteRequest {\n");
    
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    dynamicMappings: ").append(toIndentedString(dynamicMappings)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    mappingClaim: ").append(toIndentedString(mappingClaim)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    providerUrl: ").append(toIndentedString(providerUrl)).append("\n");
    sb.append("    serviceAccounts: ").append(toIndentedString(serviceAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

