/*
 * Cloudsmith API
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RepositoryAuditLog
 */

public class RepositoryAuditLog implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("actor")
  private String actor = null;

  @SerializedName("actor_ip_address")
  private String actorIpAddress = null;

  @SerializedName("actor_kind")
  private String actorKind = null;

  @SerializedName("actor_location")
  private Object actorLocation = null;

  @SerializedName("actor_slug_perm")
  private String actorSlugPerm = null;

  @SerializedName("actor_url")
  private String actorUrl = null;

  @SerializedName("context")
  private String context = null;

  @SerializedName("event")
  private String event = null;

  @SerializedName("event_at")
  private String eventAt = null;

  @SerializedName("object")
  private String object = null;

  @SerializedName("object_kind")
  private String objectKind = null;

  @SerializedName("object_slug_perm")
  private String objectSlugPerm = null;

  @SerializedName("uuid")
  private String uuid = null;

  public RepositoryAuditLog actor(String actor) {
    this.actor = actor;
    return this;
  }

   /**
   * 
   * @return actor
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getActor() {
    return actor;
  }

  public void setActor(String actor) {
    this.actor = actor;
  }

  public RepositoryAuditLog actorIpAddress(String actorIpAddress) {
    this.actorIpAddress = actorIpAddress;
    return this;
  }

   /**
   * 
   * @return actorIpAddress
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getActorIpAddress() {
    return actorIpAddress;
  }

  public void setActorIpAddress(String actorIpAddress) {
    this.actorIpAddress = actorIpAddress;
  }

  public RepositoryAuditLog actorKind(String actorKind) {
    this.actorKind = actorKind;
    return this;
  }

   /**
   * 
   * @return actorKind
  **/
  @ApiModelProperty(value = "")
  public String getActorKind() {
    return actorKind;
  }

  public void setActorKind(String actorKind) {
    this.actorKind = actorKind;
  }

  public RepositoryAuditLog actorLocation(Object actorLocation) {
    this.actorLocation = actorLocation;
    return this;
  }

   /**
   * 
   * @return actorLocation
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public Object getActorLocation() {
    return actorLocation;
  }

  public void setActorLocation(Object actorLocation) {
    this.actorLocation = actorLocation;
  }

  public RepositoryAuditLog actorSlugPerm(String actorSlugPerm) {
    this.actorSlugPerm = actorSlugPerm;
    return this;
  }

   /**
   * 
   * @return actorSlugPerm
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getActorSlugPerm() {
    return actorSlugPerm;
  }

  public void setActorSlugPerm(String actorSlugPerm) {
    this.actorSlugPerm = actorSlugPerm;
  }

  public RepositoryAuditLog actorUrl(String actorUrl) {
    this.actorUrl = actorUrl;
    return this;
  }

   /**
   * 
   * @return actorUrl
  **/
  @ApiModelProperty(value = "")
  public String getActorUrl() {
    return actorUrl;
  }

  public void setActorUrl(String actorUrl) {
    this.actorUrl = actorUrl;
  }

  public RepositoryAuditLog context(String context) {
    this.context = context;
    return this;
  }

   /**
   * 
   * @return context
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public RepositoryAuditLog event(String event) {
    this.event = event;
    return this;
  }

   /**
   * 
   * @return event
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getEvent() {
    return event;
  }

  public void setEvent(String event) {
    this.event = event;
  }

  public RepositoryAuditLog eventAt(String eventAt) {
    this.eventAt = eventAt;
    return this;
  }

   /**
   * 
   * @return eventAt
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getEventAt() {
    return eventAt;
  }

  public void setEventAt(String eventAt) {
    this.eventAt = eventAt;
  }

  public RepositoryAuditLog object(String object) {
    this.object = object;
    return this;
  }

   /**
   * 
   * @return object
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  public RepositoryAuditLog objectKind(String objectKind) {
    this.objectKind = objectKind;
    return this;
  }

   /**
   * 
   * @return objectKind
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getObjectKind() {
    return objectKind;
  }

  public void setObjectKind(String objectKind) {
    this.objectKind = objectKind;
  }

  public RepositoryAuditLog objectSlugPerm(String objectSlugPerm) {
    this.objectSlugPerm = objectSlugPerm;
    return this;
  }

   /**
   * 
   * @return objectSlugPerm
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  public String getObjectSlugPerm() {
    return objectSlugPerm;
  }

  public void setObjectSlugPerm(String objectSlugPerm) {
    this.objectSlugPerm = objectSlugPerm;
  }

  public RepositoryAuditLog uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * 
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryAuditLog repositoryAuditLog = (RepositoryAuditLog) o;
    return Objects.equals(this.actor, repositoryAuditLog.actor) &&
        Objects.equals(this.actorIpAddress, repositoryAuditLog.actorIpAddress) &&
        Objects.equals(this.actorKind, repositoryAuditLog.actorKind) &&
        Objects.equals(this.actorLocation, repositoryAuditLog.actorLocation) &&
        Objects.equals(this.actorSlugPerm, repositoryAuditLog.actorSlugPerm) &&
        Objects.equals(this.actorUrl, repositoryAuditLog.actorUrl) &&
        Objects.equals(this.context, repositoryAuditLog.context) &&
        Objects.equals(this.event, repositoryAuditLog.event) &&
        Objects.equals(this.eventAt, repositoryAuditLog.eventAt) &&
        Objects.equals(this.object, repositoryAuditLog.object) &&
        Objects.equals(this.objectKind, repositoryAuditLog.objectKind) &&
        Objects.equals(this.objectSlugPerm, repositoryAuditLog.objectSlugPerm) &&
        Objects.equals(this.uuid, repositoryAuditLog.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actor, actorIpAddress, actorKind, actorLocation, actorSlugPerm, actorUrl, context, event, eventAt, object, objectKind, objectSlugPerm, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryAuditLog {\n");
    
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    actorIpAddress: ").append(toIndentedString(actorIpAddress)).append("\n");
    sb.append("    actorKind: ").append(toIndentedString(actorKind)).append("\n");
    sb.append("    actorLocation: ").append(toIndentedString(actorLocation)).append("\n");
    sb.append("    actorSlugPerm: ").append(toIndentedString(actorSlugPerm)).append("\n");
    sb.append("    actorUrl: ").append(toIndentedString(actorUrl)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    eventAt: ").append(toIndentedString(eventAt)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    objectKind: ").append(toIndentedString(objectKind)).append("\n");
    sb.append("    objectSlugPerm: ").append(toIndentedString(objectSlugPerm)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

