/*
 * Cloudsmith API
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ReposownerGpgKeys
 */

public class ReposownerGpgKeys implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("public_key")
  private String publicKey = null;

  @SerializedName("fingerprint_short")
  private String fingerprintShort = null;

  @SerializedName("default")
  private Boolean _default = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("fingerprint_long")
  private String fingerprintLong = null;

  @SerializedName("active")
  private Boolean active = null;

  public ReposownerGpgKeys comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * 
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public ReposownerGpgKeys publicKey(String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * The public key given to repository users.
   * @return publicKey
  **/
  @ApiModelProperty(value = "The public key given to repository users.")
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public ReposownerGpgKeys fingerprintShort(String fingerprintShort) {
    this.fingerprintShort = fingerprintShort;
    return this;
  }

   /**
   * The short identifier used by GPG for this key.
   * @return fingerprintShort
  **/
  @ApiModelProperty(value = "The short identifier used by GPG for this key.")
  public String getFingerprintShort() {
    return fingerprintShort;
  }

  public void setFingerprintShort(String fingerprintShort) {
    this.fingerprintShort = fingerprintShort;
  }

  public ReposownerGpgKeys _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * If selected this is the default key for this repository.
   * @return _default
  **/
  @ApiModelProperty(value = "If selected this is the default key for this repository.")
  public Boolean getDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public ReposownerGpgKeys createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ReposownerGpgKeys fingerprintLong(String fingerprintLong) {
    this.fingerprintLong = fingerprintLong;
    return this;
  }

   /**
   * The long identifier used by GPG for this key.
   * @return fingerprintLong
  **/
  @ApiModelProperty(value = "The long identifier used by GPG for this key.")
  public String getFingerprintLong() {
    return fingerprintLong;
  }

  public void setFingerprintLong(String fingerprintLong) {
    this.fingerprintLong = fingerprintLong;
  }

  public ReposownerGpgKeys active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * If selected this is the active key for this repository.
   * @return active
  **/
  @ApiModelProperty(value = "If selected this is the active key for this repository.")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReposownerGpgKeys reposownerGpgKeys = (ReposownerGpgKeys) o;
    return Objects.equals(this.comment, reposownerGpgKeys.comment) &&
        Objects.equals(this.publicKey, reposownerGpgKeys.publicKey) &&
        Objects.equals(this.fingerprintShort, reposownerGpgKeys.fingerprintShort) &&
        Objects.equals(this._default, reposownerGpgKeys._default) &&
        Objects.equals(this.createdAt, reposownerGpgKeys.createdAt) &&
        Objects.equals(this.fingerprintLong, reposownerGpgKeys.fingerprintLong) &&
        Objects.equals(this.active, reposownerGpgKeys.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, publicKey, fingerprintShort, _default, createdAt, fingerprintLong, active);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReposownerGpgKeys {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    fingerprintShort: ").append(toIndentedString(fingerprintShort)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    fingerprintLong: ").append(toIndentedString(fingerprintLong)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

