/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.cloudsmith.api.models.ServiceTeams;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Service
 */

public class Service implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("created_by")
  private String createdBy = null;

  @SerializedName("created_by_url")
  private String createdByUrl = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("key_expires_at")
  private OffsetDateTime keyExpiresAt = null;

  @SerializedName("name")
  private String name = null;

  /**
   * The role of the service.
   */
  @JsonAdapter(RoleEnum.Adapter.class)
  public enum RoleEnum {
    MANAGER("Manager"),
    
    MEMBER("Member");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RoleEnum fromValue(String text) {
      for (RoleEnum b : RoleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RoleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RoleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RoleEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RoleEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("role")
  private RoleEnum role = RoleEnum.MEMBER;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("teams")
  private List<ServiceTeams> teams = null;

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Valid
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
 @Size(min=1)  @ApiModelProperty(value = "")
  public String getCreatedBy() {
    return createdBy;
  }

   /**
   * Get createdByUrl
   * @return createdByUrl
  **/
  @ApiModelProperty(value = "")
  public String getCreatedByUrl() {
    return createdByUrl;
  }

  public Service description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the service
   * @return description
  **/
 @Size(min=1,max=1024)  @ApiModelProperty(value = "The description of the service")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * The API key of the service
   * @return key
  **/
  @ApiModelProperty(value = "The API key of the service")
  public String getKey() {
    return key;
  }

   /**
   * The time at which the API key will expire. This will only be populated if the Organization has an active API Key Policy.
   * @return keyExpiresAt
  **/
  @Valid
  @ApiModelProperty(value = "The time at which the API key will expire. This will only be populated if the Organization has an active API Key Policy.")
  public OffsetDateTime getKeyExpiresAt() {
    return keyExpiresAt;
  }

  public Service name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the service
   * @return name
  **/
  @NotNull
 @Size(min=1,max=120)  @ApiModelProperty(required = true, value = "The name of the service")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Service role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * The role of the service.
   * @return role
  **/
  @ApiModelProperty(value = "The role of the service.")
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

   /**
   * The slug of the service
   * @return slug
  **/
 @Pattern(regexp="^[-a-zA-Z0-9_]+$") @Size(min=1)  @ApiModelProperty(value = "The slug of the service")
  public String getSlug() {
    return slug;
  }

  public Service teams(List<ServiceTeams> teams) {
    this.teams = teams;
    return this;
  }

  public Service addTeamsItem(ServiceTeams teamsItem) {
    if (this.teams == null) {
      this.teams = new ArrayList<>();
    }
    this.teams.add(teamsItem);
    return this;
  }

   /**
   * Get teams
   * @return teams
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<ServiceTeams> getTeams() {
    return teams;
  }

  public void setTeams(List<ServiceTeams> teams) {
    this.teams = teams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.createdAt, service.createdAt) &&
        Objects.equals(this.createdBy, service.createdBy) &&
        Objects.equals(this.createdByUrl, service.createdByUrl) &&
        Objects.equals(this.description, service.description) &&
        Objects.equals(this.key, service.key) &&
        Objects.equals(this.keyExpiresAt, service.keyExpiresAt) &&
        Objects.equals(this.name, service.name) &&
        Objects.equals(this.role, service.role) &&
        Objects.equals(this.slug, service.slug) &&
        Objects.equals(this.teams, service.teams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, createdBy, createdByUrl, description, key, keyExpiresAt, name, role, slug, teams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdByUrl: ").append(toIndentedString(createdByUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    keyExpiresAt: ").append(toIndentedString(keyExpiresAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

