/*
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.cloudsmith.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * UserProfileResponse
 */

public class UserProfileResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("company")
  private String company = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("job_title")
  private String jobTitle = null;

  @SerializedName("joined_at")
  private OffsetDateTime joinedAt = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("slug_perm")
  private String slugPerm = null;

  @SerializedName("tagline")
  private String tagline = null;

  @SerializedName("url")
  private String url = null;

  public UserProfileResponse company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
 @Size(max=64)  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public UserProfileResponse firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @NotNull
 @Size(min=1,max=40)  @ApiModelProperty(required = true, value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserProfileResponse jobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
 @Size(max=64)  @ApiModelProperty(value = "")
  public String getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }

  public UserProfileResponse joinedAt(OffsetDateTime joinedAt) {
    this.joinedAt = joinedAt;
    return this;
  }

   /**
   * Get joinedAt
   * @return joinedAt
  **/
  @Valid
  @ApiModelProperty(value = "")
  public OffsetDateTime getJoinedAt() {
    return joinedAt;
  }

  public void setJoinedAt(OffsetDateTime joinedAt) {
    this.joinedAt = joinedAt;
  }

  public UserProfileResponse lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @NotNull
 @Size(min=1,max=30)  @ApiModelProperty(required = true, value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

   /**
   * Get name
   * @return name
  **/
 @Size(min=1)  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

   /**
   * Get slug
   * @return slug
  **/
  @ApiModelProperty(value = "")
  public String getSlug() {
    return slug;
  }

   /**
   * Get slugPerm
   * @return slugPerm
  **/
  @ApiModelProperty(value = "")
  public String getSlugPerm() {
    return slugPerm;
  }

  public UserProfileResponse tagline(String tagline) {
    this.tagline = tagline;
    return this;
  }

   /**
   * Your tagline is a sentence about you. Make it funny. Make it professional. Either way, it&#39;s public and it represents who you are.
   * @return tagline
  **/
 @Size(max=80)  @ApiModelProperty(value = "Your tagline is a sentence about you. Make it funny. Make it professional. Either way, it's public and it represents who you are.")
  public String getTagline() {
    return tagline;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileResponse userProfileResponse = (UserProfileResponse) o;
    return Objects.equals(this.company, userProfileResponse.company) &&
        Objects.equals(this.firstName, userProfileResponse.firstName) &&
        Objects.equals(this.jobTitle, userProfileResponse.jobTitle) &&
        Objects.equals(this.joinedAt, userProfileResponse.joinedAt) &&
        Objects.equals(this.lastName, userProfileResponse.lastName) &&
        Objects.equals(this.name, userProfileResponse.name) &&
        Objects.equals(this.slug, userProfileResponse.slug) &&
        Objects.equals(this.slugPerm, userProfileResponse.slugPerm) &&
        Objects.equals(this.tagline, userProfileResponse.tagline) &&
        Objects.equals(this.url, userProfileResponse.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, firstName, jobTitle, joinedAt, lastName, name, slug, slugPerm, tagline, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileResponse {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    joinedAt: ").append(toIndentedString(joinedAt)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    slugPerm: ").append(toIndentedString(slugPerm)).append("\n");
    sb.append("    tagline: ").append(toIndentedString(tagline)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

