version: 2.1
commands:
  prepare_build_environment:
    description: "Install the tools necessary to build the bindings"
    steps:
      - run:
          command: |
            sudo apt update
            sudo apt install -y git-lfs
            git lfs install
            git lfs pull
  build_bindings:
    description: "Build the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - run: ./scripts/build.sh <<parameters.language>>
  cache_bindings:
    description: "Cache the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - save_cache:
          paths:
            - ./bindings/<<parameters.language>>/src
          key: <<parameters.language>>-bindings-{{ .Revision }}
  restore_bindings:
    description: "Restore the cached bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - restore_cache:
          key: <<parameters.language>>-bindings-{{ .Revision }}
  test_bindings:
    description: "Test the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - run: ./scripts/test.sh <<parameters.language>>
  prepare_deploy_environment:
    description: "Prepare the environment used to deploy the API bindings"
    steps:
      - run:
          command: |
            sudo apt update
            sudo apt-get install --no-upgrade -y gettext python python-pip
            pip install --no-cache --user cloudsmith-cli
  deploy_bindings:
    description: "Deploy the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - run: ./scripts/deploy.sh <<parameters.language>>

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - prepare_build_environment
      - build_bindings:
          language: "java"
      - build_bindings:
          language: "go"
      - build_bindings:
          language: "python"
      - build_bindings:
          language: "ruby"
      - cache_bindings:
          language: "java"
      - cache_bindings:
          language: "go"
      - cache_bindings:
          language: "python"
      - cache_bindings:
          language: "ruby"
  test:
    description: "Tests the bindings for a language"
    parameters:
      docker_image:
        type: string
      language:
        type: string
    docker:
      - image: <<parameters.docker_image>>
    steps:
      - checkout
      - restore_bindings:
          language: <<parameters.language>>
      - test_bindings:
          language: <<parameters.language>>
  deploy_bindings:
    description: "Deploys the bindings for a language"
    parameters:
      docker_image:
        type: string
      language:
        type: string
    docker:
      - image: <<parameters.docker_image>>
        auth:
          username: cloudsmith/circleci-images
          password: $CLOUDSMITH_PRODUCTION_API_KEY
    steps:
      - checkout
      - restore_bindings:
          language: <<parameters.language>>
      - prepare_deploy_environment
      - deploy_bindings:
          language: <<parameters.language>>

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          name: "Test Java"
          language: java
          docker_image: circleci/openjdk:8
      - deploy_bindings:
          requires:
            - "Test Java"
          # filters:
          #   branches:
          #     only:
          #       - master
          name: "Deploy Java"
          language: java
          docker_image: circleci/openjdk:8
      - test:
          requires:
            - build
          name: "Test Go"
          language: go
          docker_image: circleci/golang:1.13
      - deploy_bindings:
          requires:
            - "Test Go"
          # filters:
          #   branches:
          #    only:
          #      - master
          name: "Deploy Go"
          language: go
          docker_image: docker.cloudsmith.io/cloudsmith/circleci-images/go:1.13-rc
      - test:
          requires:
            - build
          name: "Test Ruby"
          language: ruby
          docker_image: circleci/ruby:2.6
      - deploy_bindings:
          requires:
            - "Test Ruby"
          # filters:
          #   branches:
          #    only:
          #      - master
          name: "Deploy Ruby"
          language: ruby
          docker_image: docker.cloudsmith.io/cloudsmith/circleci-images/ruby:2.6.1
      - test:
          requires:
            - build
          name: "Test Python"
          language: python
          docker_image: circleci/python:3.7
      - deploy_bindings:
          requires:
            - "Test Python"
          # filters:
          #   branches:
          #    only:
          #      - master
          name: "Deploy Python"
          language: python
          docker_image: docker.cloudsmith.io/cloudsmith/circleci-images/python:3.7.2
