version: 2.1
commands:
  test_bindings:
    description: "Test the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - run: ./scripts/test.sh <<parameters.language>>
  prepare_deploy_environment:
    description: "Prepare the environment used to deploy the API bindings"
    steps:
      - run:
          command: |
            sudo apt update
            sudo apt-get install --no-upgrade -y gettext python3 python3-pip
            pip3 install --no-cache --upgrade --user cloudsmith-cli
  deploy_bindings:
    description: "Deploy the bindings for a language"
    parameters:
      language:
        type: string
    steps:
      - run: ./scripts/deploy.sh <<parameters.language>>

jobs:
  test:
    description: "Tests the bindings for a language"
    parameters:
      docker_image:
        type: string
      language:
        type: string
      extra_env:
        type: string
        default: "EXAMPLE_KEY=EXAMPLE_VALUE"
    docker:
      - image: <<parameters.docker_image>>
    steps:
      - checkout
      - run:
          name: "Injecting additional environment variables"
          command: |
            [ -n "<<parameters.extra_env>>" ] && echo "export <<parameters.extra_env>>" >> $BASH_ENV
      - test_bindings:
          language: <<parameters.language>>
  deploy_bindings:
    description: "Deploys the bindings for a language"
    parameters:
      docker_image:
        type: string
      language:
        type: string
    docker:
      - image: <<parameters.docker_image>>
    steps:
      - checkout
      - prepare_deploy_environment
      - deploy_bindings:
          language: <<parameters.language>>

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          name: "Test Java"
          language: java
          docker_image: cimg/openjdk:8.0
      - deploy_bindings:
          requires:
            - "Test Java"
          filters:
            branches:
              only:
                - master
          name: "Deploy Java"
          language: java
          docker_image: cimg/openjdk:8.0
      - test:
          name: "Test Go"
          language: go
          docker_image: cimg/go:1.13
      - deploy_bindings:
          requires:
            - "Test Go"
          filters:
            branches:
             only:
               - master
          name: "Deploy Go"
          language: go
          docker_image: cimg/go:1.13
      - test:
          name: "Test Ruby"
          language: ruby
          docker_image: cimg/ruby:2.6
      - deploy_bindings:
          requires:
            - "Test Ruby"
          filters:
            branches:
             only:
               - master
          name: "Deploy Ruby"
          language: ruby
          docker_image: cimg/ruby:2.6
      - test:
          name: "Test Python 2.7"
          language: python
          extra_env: TOXENV=py27
          docker_image: cimg/python:2.7
      - test:
          name: "Test Python 3.7"
          language: python
          extra_env: TOXENV=py3
          docker_image: cimg/python:3.7
      - deploy_bindings:
          requires:
            - "Test Python 2.7"
            - "Test Python 3.7"
          filters:
            branches:
             only:
               - master
          name: "Deploy Python"
          language: python
          docker_image: cimg/python:3.7
