=begin
#Cloudsmith API (v1)

#The API to the Cloudsmith Service

OpenAPI spec version: v1
Contact: support@cloudsmith.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.50

=end

require 'date'

module CloudsmithApi
class PackageLicenseRequestPatch
  attr_accessor :action

  attr_accessor :license_notes

  attr_accessor :license_override

  attr_accessor :license_url

  attr_accessor :spdx_license

  class EnumAttributeValidator
    attr_reader :datatype
    attr_reader :allowable_values

    def initialize(datatype, allowable_values)
      @allowable_values = allowable_values.map do |value|
        case datatype.to_s
        when /Integer/i
          value.to_i
        when /Float/i
          value.to_f
        else
          value
        end
      end
    end

    def valid?(value)
      !value || allowable_values.include?(value)
    end
  end

  # Attribute mapping from ruby-style variable name to JSON key.
  def self.attribute_map
    {
      :'action' => :'action',
      :'license_notes' => :'license_notes',
      :'license_override' => :'license_override',
      :'license_url' => :'license_url',
      :'spdx_license' => :'spdx_license'
    }
  end

  # Attribute type mapping.
  def self.swagger_types
    {
      :'action' => :'String',
      :'license_notes' => :'String',
      :'license_override' => :'String',
      :'license_url' => :'String',
      :'spdx_license' => :'String'
    }
  end

  # Initializes the object
  # @param [Hash] attributes Model attributes in the form of hash
  def initialize(attributes = {})
    return unless attributes.is_a?(Hash)

    # convert string to symbol for hash key
    attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

    if attributes.has_key?(:'action')
      self.action = attributes[:'action']
    else
      self.action = 'Update'
    end

    if attributes.has_key?(:'license_notes')
      self.license_notes = attributes[:'license_notes']
    end

    if attributes.has_key?(:'license_override')
      self.license_override = attributes[:'license_override']
    else
      self.license_override = 'None'
    end

    if attributes.has_key?(:'license_url')
      self.license_url = attributes[:'license_url']
    end

    if attributes.has_key?(:'spdx_license')
      self.spdx_license = attributes[:'spdx_license']
    end
  end

  # Show invalid properties with the reasons. Usually used together with valid?
  # @return Array for valid properties with the reasons
  def list_invalid_properties
    invalid_properties = Array.new
    invalid_properties
  end

  # Check to see if the all the properties in the model are valid
  # @return true if the model is valid
  def valid?
    action_validator = EnumAttributeValidator.new('String', ['Update'])
    return false unless action_validator.valid?(@action)
    license_override_validator = EnumAttributeValidator.new('String', ['None', 'Ignored', 'Purchased'])
    return false unless license_override_validator.valid?(@license_override)
    true
  end

  # Custom attribute writer method checking allowed values (enum).
  # @param [Object] action Object to be assigned
  def action=(action)
    validator = EnumAttributeValidator.new('String', ['Update'])
    unless validator.valid?(action)
      fail ArgumentError, 'invalid value for "action", must be one of #{validator.allowable_values}.'
    end
    @action = action
  end

  # Custom attribute writer method checking allowed values (enum).
  # @param [Object] license_override Object to be assigned
  def license_override=(license_override)
    validator = EnumAttributeValidator.new('String', ['None', 'Ignored', 'Purchased'])
    unless validator.valid?(license_override)
      fail ArgumentError, 'invalid value for "license_override", must be one of #{validator.allowable_values}.'
    end
    @license_override = license_override
  end

  # Checks equality by comparing each attribute.
  # @param [Object] Object to be compared
  def ==(o)
    return true if self.equal?(o)
    self.class == o.class &&
        action == o.action &&
        license_notes == o.license_notes &&
        license_override == o.license_override &&
        license_url == o.license_url &&
        spdx_license == o.spdx_license
  end

  # @see the `==` method
  # @param [Object] Object to be compared
  def eql?(o)
    self == o
  end

  # Calculates hash code according to all attributes.
  # @return [Fixnum] Hash code
  def hash
    [action, license_notes, license_override, license_url, spdx_license].hash
  end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudsmithApi.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

end
end
