=begin
#Cloudsmith API

#The API to the Cloudsmith Service

OpenAPI spec version: v1
Contact: support@cloudsmith.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudsmithApi::FilesValidate
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FilesValidate' do
  before do
    # run before each test
    @instance = CloudsmithApi::FilesValidate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilesValidate' do
    it 'should create an instance of FilesValidate' do
      expect(@instance).to be_instance_of(CloudsmithApi::FilesValidate)
    end
  end
  describe 'test attribute "filename"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "md5_checksum"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

