=begin
#Cloudsmith API (v1)

#The API to the Cloudsmith Service

OpenAPI spec version: v1
Contact: support@cloudsmith.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.50

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudsmithApi::OpenidApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OpenidApi' do
  before do
    # run before each test
    @instance = CloudsmithApi::OpenidApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OpenidApi' do
    it 'should create an instance of OpenidApi' do
      expect(@instance).to be_instance_of(CloudsmithApi::OpenidApi)
    end
  end

  # unit tests for openid_create
  # Get a JWT token for a configured service account belonging to the requesting org.
  # Get a JWT token for a configured service account belonging to the requesting org.
  # @param owner 
  # @param [Hash] opts the optional parameters
  # @option opts [OidcRequest] :data 
  # @return [Oidc1]
  describe 'openid_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
