/* 
 * Cloudsmith API (v1)
 *
 * The API to the Cloudsmith Service
 *
 * OpenAPI spec version: v1
 * Contact: support@cloudsmith.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PackageLicensePolicyViolationLog {
  #[serde(rename = "event_at")]
  event_at: Option<String>,
  #[serde(rename = "package")]
  package: ::models::PackageVulnerability,
  #[serde(rename = "policy")]
  policy: ::models::NestedLicensePolicy,
  #[serde(rename = "reasons")]
  reasons: Vec<String>
}

impl PackageLicensePolicyViolationLog {
  pub fn new(package: ::models::PackageVulnerability, policy: ::models::NestedLicensePolicy, reasons: Vec<String>) -> PackageLicensePolicyViolationLog {
    PackageLicensePolicyViolationLog {
      event_at: None,
      package: package,
      policy: policy,
      reasons: reasons
    }
  }

  pub fn set_event_at(&mut self, event_at: String) {
    self.event_at = Some(event_at);
  }

  pub fn with_event_at(mut self, event_at: String) -> PackageLicensePolicyViolationLog {
    self.event_at = Some(event_at);
    self
  }

  pub fn event_at(&self) -> Option<&String> {
    self.event_at.as_ref()
  }

  pub fn reset_event_at(&mut self) {
    self.event_at = None;
  }

  pub fn set_package(&mut self, package: ::models::PackageVulnerability) {
    self.package = package;
  }

  pub fn with_package(mut self, package: ::models::PackageVulnerability) -> PackageLicensePolicyViolationLog {
    self.package = package;
    self
  }

  pub fn package(&self) -> &::models::PackageVulnerability {
    &self.package
  }


  pub fn set_policy(&mut self, policy: ::models::NestedLicensePolicy) {
    self.policy = policy;
  }

  pub fn with_policy(mut self, policy: ::models::NestedLicensePolicy) -> PackageLicensePolicyViolationLog {
    self.policy = policy;
    self
  }

  pub fn policy(&self) -> &::models::NestedLicensePolicy {
    &self.policy
  }


  pub fn set_reasons(&mut self, reasons: Vec<String>) {
    self.reasons = reasons;
  }

  pub fn with_reasons(mut self, reasons: Vec<String>) -> PackageLicensePolicyViolationLog {
    self.reasons = reasons;
    self
  }

  pub fn reasons(&self) -> &Vec<String> {
    &self.reasons
  }


}



