/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllocatedLimitRaw
 */
export interface AllocatedLimitRaw {
    /**
     * 
     * @type {number}
     * @memberof AllocatedLimitRaw
     */
    configured?: number;
    /**
     * 
     * @type {string}
     * @memberof AllocatedLimitRaw
     */
    percentage_used?: string;
    /**
     * 
     * @type {number}
     * @memberof AllocatedLimitRaw
     */
    plan_limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AllocatedLimitRaw
     */
    used?: number;
}

/**
 * Check if a given object implements the AllocatedLimitRaw interface.
 */
export function instanceOfAllocatedLimitRaw(value: object): value is AllocatedLimitRaw {
    return true;
}

export function AllocatedLimitRawFromJSON(json: any): AllocatedLimitRaw {
    return AllocatedLimitRawFromJSONTyped(json, false);
}

export function AllocatedLimitRawFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocatedLimitRaw {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'percentage_used': json['percentage_used'] == null ? undefined : json['percentage_used'],
        'plan_limit': json['plan_limit'] == null ? undefined : json['plan_limit'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function AllocatedLimitRawToJSON(json: any): AllocatedLimitRaw {
    return AllocatedLimitRawToJSONTyped(json, false);
}

export function AllocatedLimitRawToJSONTyped(value?: AllocatedLimitRaw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'percentage_used': value['percentage_used'],
        'plan_limit': value['plan_limit'],
        'used': value['used'],
    };
}

