/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebUpstream
 */
export interface DebUpstream {
    /**
     * The authentication mode to use when accessing this upstream. 
     * @type {string}
     * @memberof DebUpstream
     */
    auth_mode?: DebUpstreamAuthModeEnum;
    /**
     * Secret to provide with requests to upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    auth_secret?: string | null;
    /**
     * Username to provide with requests to upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    auth_username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly available?: string;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly can_reindex?: string;
    /**
     * The component to fetch from the upstream
     * @type {string}
     * @memberof DebUpstream
     */
    component?: string;
    /**
     * The datetime the upstream source was created.
     * @type {Date}
     * @memberof DebUpstream
     */
    readonly created_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly disable_reason?: DebUpstreamDisableReasonEnum;
    /**
     * Human-readable explanation of why this upstream is disabled
     * @type {string}
     * @memberof DebUpstream
     */
    readonly disable_reason_text?: string;
    /**
     * The distribution version that packages found on this upstream could be associated with.
     * @type {Set<string>}
     * @memberof DebUpstream
     */
    distro_versions: Set<string>;
    /**
     * The key for extra header #1 to send to upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    extra_header_1?: string | null;
    /**
     * The key for extra header #2 to send to upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    extra_header_2?: string | null;
    /**
     * The value for extra header #1 to send to upstream. This is stored as plaintext, and is NOT encrypted.
     * @type {string}
     * @memberof DebUpstream
     */
    extra_value_1?: string | null;
    /**
     * The value for extra header #2 to send to upstream. This is stored as plaintext, and is NOT encrypted.
     * @type {string}
     * @memberof DebUpstream
     */
    extra_value_2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly gpg_key_fingerprint_short?: string;
    /**
     * A public GPG key to associate with packages found on this upstream. When using the Cloudsmith setup script, this GPG key will be automatically imported on your deployment machines to allow upstream packages to validate and install.
     * @type {string}
     * @memberof DebUpstream
     */
    gpg_key_inline?: string | null;
    /**
     * When provided, Cloudsmith will fetch, validate, and associate a public GPG key found at the provided URL. When using the Cloudsmith setup script, this GPG key will be automatically imported on your deployment machines to allow upstream packages to validate and install.
     * @type {string}
     * @memberof DebUpstream
     */
    gpg_key_url?: string | null;
    /**
     * The GPG signature verification mode for this upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    gpg_verification?: DebUpstreamGpgVerificationEnum;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly has_failed_signature_verification?: string;
    /**
     * When true, source packages will be available from this upstream.
     * @type {boolean}
     * @memberof DebUpstream
     */
    include_sources?: boolean;
    /**
     * The number of packages available in this upstream source
     * @type {string}
     * @memberof DebUpstream
     */
    readonly index_package_count?: string;
    /**
     * The current indexing status of this upstream source
     * @type {string}
     * @memberof DebUpstream
     */
    readonly index_status?: string;
    /**
     * Whether or not this upstream is active and ready for requests.
     * @type {boolean}
     * @memberof DebUpstream
     */
    is_active?: boolean;
    /**
     * The last time this upstream source was indexed
     * @type {string}
     * @memberof DebUpstream
     */
    readonly last_indexed?: string;
    /**
     * The mode that this upstream should operate in. Upstream sources can be used to proxy resolved packages, as well as operate in a proxy/cache or cache only mode.
     * @type {string}
     * @memberof DebUpstream
     */
    mode?: DebUpstreamModeEnum;
    /**
     * A descriptive name for this upstream source. A shortened version of this name will be used for tagging cached packages retrieved from this upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    name: string;
    /**
     * When true, this upstream source is pending validation.
     * @type {boolean}
     * @memberof DebUpstream
     */
    readonly pending_validation?: boolean;
    /**
     * Upstream sources are selected for resolving requests by sequential order (1..n), followed by creation date.
     * @type {number}
     * @memberof DebUpstream
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof DebUpstream
     */
    readonly slug_perm?: string;
    /**
     * 
     * @type {Date}
     * @memberof DebUpstream
     */
    readonly updated_at?: Date;
    /**
     * The distribution to fetch from the upstream
     * @type {string}
     * @memberof DebUpstream
     */
    upstream_distribution?: string | null;
    /**
     * The URL for this upstream source. This must be a fully qualified URL including any path elements required to reach the root of the repository. 
     * @type {string}
     * @memberof DebUpstream
     */
    upstream_url: string;
    /**
     * The signature verification status for this upstream.
     * @type {string}
     * @memberof DebUpstream
     */
    readonly verification_status?: DebUpstreamVerificationStatusEnum;
    /**
     * If enabled, SSL certificates are verified when requests are made to this upstream. It's recommended to leave this enabled for all public sources to help mitigate Man-In-The-Middle (MITM) attacks. Please note this only applies to HTTPS upstreams.
     * @type {boolean}
     * @memberof DebUpstream
     */
    verify_ssl?: boolean;
}


/**
 * @export
 */
export const DebUpstreamAuthModeEnum = {
    None: 'None',
    Username_and_Password: 'Username and Password'
} as const;
export type DebUpstreamAuthModeEnum = typeof DebUpstreamAuthModeEnum[keyof typeof DebUpstreamAuthModeEnum];

/**
 * @export
 */
export const DebUpstreamDisableReasonEnum = {
    N_A: 'N/A',
    Upstream_points_to_its_own_repository: 'Upstream points to its own repository',
    Missing_upstream_source: 'Missing upstream source',
    Upstream_was_disabled_by_request_of_user: 'Upstream was disabled by request of user'
} as const;
export type DebUpstreamDisableReasonEnum = typeof DebUpstreamDisableReasonEnum[keyof typeof DebUpstreamDisableReasonEnum];

/**
 * @export
 */
export const DebUpstreamGpgVerificationEnum = {
    Allow_All: 'Allow All',
    Warn_on_Invalid: 'Warn on Invalid',
    Reject_Invalid: 'Reject Invalid'
} as const;
export type DebUpstreamGpgVerificationEnum = typeof DebUpstreamGpgVerificationEnum[keyof typeof DebUpstreamGpgVerificationEnum];

/**
 * @export
 */
export const DebUpstreamModeEnum = {
    Proxy_Only: 'Proxy Only',
    Cache_and_Proxy: 'Cache and Proxy'
} as const;
export type DebUpstreamModeEnum = typeof DebUpstreamModeEnum[keyof typeof DebUpstreamModeEnum];

/**
 * @export
 */
export const DebUpstreamVerificationStatusEnum = {
    Unknown: 'Unknown',
    Invalid: 'Invalid',
    Valid: 'Valid',
    Invalid__No_Key: 'Invalid (No Key)'
} as const;
export type DebUpstreamVerificationStatusEnum = typeof DebUpstreamVerificationStatusEnum[keyof typeof DebUpstreamVerificationStatusEnum];


/**
 * Check if a given object implements the DebUpstream interface.
 */
export function instanceOfDebUpstream(value: object): value is DebUpstream {
    if (!('distro_versions' in value) || value['distro_versions'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('upstream_url' in value) || value['upstream_url'] === undefined) return false;
    return true;
}

export function DebUpstreamFromJSON(json: any): DebUpstream {
    return DebUpstreamFromJSONTyped(json, false);
}

export function DebUpstreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebUpstream {
    if (json == null) {
        return json;
    }
    return {
        
        'auth_mode': json['auth_mode'] == null ? undefined : json['auth_mode'],
        'auth_secret': json['auth_secret'] == null ? undefined : json['auth_secret'],
        'auth_username': json['auth_username'] == null ? undefined : json['auth_username'],
        'available': json['available'] == null ? undefined : json['available'],
        'can_reindex': json['can_reindex'] == null ? undefined : json['can_reindex'],
        'component': json['component'] == null ? undefined : json['component'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'disable_reason': json['disable_reason'] == null ? undefined : json['disable_reason'],
        'disable_reason_text': json['disable_reason_text'] == null ? undefined : json['disable_reason_text'],
        'distro_versions': new Set(json['distro_versions']),
        'extra_header_1': json['extra_header_1'] == null ? undefined : json['extra_header_1'],
        'extra_header_2': json['extra_header_2'] == null ? undefined : json['extra_header_2'],
        'extra_value_1': json['extra_value_1'] == null ? undefined : json['extra_value_1'],
        'extra_value_2': json['extra_value_2'] == null ? undefined : json['extra_value_2'],
        'gpg_key_fingerprint_short': json['gpg_key_fingerprint_short'] == null ? undefined : json['gpg_key_fingerprint_short'],
        'gpg_key_inline': json['gpg_key_inline'] == null ? undefined : json['gpg_key_inline'],
        'gpg_key_url': json['gpg_key_url'] == null ? undefined : json['gpg_key_url'],
        'gpg_verification': json['gpg_verification'] == null ? undefined : json['gpg_verification'],
        'has_failed_signature_verification': json['has_failed_signature_verification'] == null ? undefined : json['has_failed_signature_verification'],
        'include_sources': json['include_sources'] == null ? undefined : json['include_sources'],
        'index_package_count': json['index_package_count'] == null ? undefined : json['index_package_count'],
        'index_status': json['index_status'] == null ? undefined : json['index_status'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'last_indexed': json['last_indexed'] == null ? undefined : json['last_indexed'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'name': json['name'],
        'pending_validation': json['pending_validation'] == null ? undefined : json['pending_validation'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'slug_perm': json['slug_perm'] == null ? undefined : json['slug_perm'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'upstream_distribution': json['upstream_distribution'] == null ? undefined : json['upstream_distribution'],
        'upstream_url': json['upstream_url'],
        'verification_status': json['verification_status'] == null ? undefined : json['verification_status'],
        'verify_ssl': json['verify_ssl'] == null ? undefined : json['verify_ssl'],
    };
}

export function DebUpstreamToJSON(json: any): DebUpstream {
    return DebUpstreamToJSONTyped(json, false);
}

export function DebUpstreamToJSONTyped(value?: Omit<DebUpstream, 'available'|'can_reindex'|'created_at'|'disable_reason'|'disable_reason_text'|'gpg_key_fingerprint_short'|'has_failed_signature_verification'|'index_package_count'|'index_status'|'last_indexed'|'pending_validation'|'slug_perm'|'updated_at'|'verification_status'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_mode': value['auth_mode'],
        'auth_secret': value['auth_secret'],
        'auth_username': value['auth_username'],
        'component': value['component'],
        'distro_versions': Array.from(value['distro_versions'] as Set<any>),
        'extra_header_1': value['extra_header_1'],
        'extra_header_2': value['extra_header_2'],
        'extra_value_1': value['extra_value_1'],
        'extra_value_2': value['extra_value_2'],
        'gpg_key_inline': value['gpg_key_inline'],
        'gpg_key_url': value['gpg_key_url'],
        'gpg_verification': value['gpg_verification'],
        'include_sources': value['include_sources'],
        'is_active': value['is_active'],
        'mode': value['mode'],
        'name': value['name'],
        'priority': value['priority'],
        'upstream_distribution': value['upstream_distribution'],
        'upstream_url': value['upstream_url'],
        'verify_ssl': value['verify_ssl'],
    };
}

