/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGroupSyncRequest
 */
export interface OrganizationGroupSyncRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupSyncRequest
     */
    idp_key: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupSyncRequest
     */
    idp_value: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupSyncRequest
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupSyncRequest
     */
    role?: OrganizationGroupSyncRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupSyncRequest
     */
    team: string;
}


/**
 * @export
 */
export const OrganizationGroupSyncRequestRoleEnum = {
    Manager: 'Manager',
    Member: 'Member'
} as const;
export type OrganizationGroupSyncRequestRoleEnum = typeof OrganizationGroupSyncRequestRoleEnum[keyof typeof OrganizationGroupSyncRequestRoleEnum];


/**
 * Check if a given object implements the OrganizationGroupSyncRequest interface.
 */
export function instanceOfOrganizationGroupSyncRequest(value: object): value is OrganizationGroupSyncRequest {
    if (!('idp_key' in value) || value['idp_key'] === undefined) return false;
    if (!('idp_value' in value) || value['idp_value'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    return true;
}

export function OrganizationGroupSyncRequestFromJSON(json: any): OrganizationGroupSyncRequest {
    return OrganizationGroupSyncRequestFromJSONTyped(json, false);
}

export function OrganizationGroupSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGroupSyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idp_key': json['idp_key'],
        'idp_value': json['idp_value'],
        'organization': json['organization'],
        'role': json['role'] == null ? undefined : json['role'],
        'team': json['team'],
    };
}

export function OrganizationGroupSyncRequestToJSON(json: any): OrganizationGroupSyncRequest {
    return OrganizationGroupSyncRequestToJSONTyped(json, false);
}

export function OrganizationGroupSyncRequestToJSONTyped(value?: OrganizationGroupSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idp_key': value['idp_key'],
        'idp_value': value['idp_value'],
        'organization': value['organization'],
        'role': value['role'],
        'team': value['team'],
    };
}

