/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PythonPackageUploadRequest
 */
export interface PythonPackageUploadRequest {
    /**
     * The primary file for the package.
     * @type {string}
     * @memberof PythonPackageUploadRequest
     */
    package_file: string;
    /**
     * If true, the uploaded package will overwrite any others with the same attributes (e.g. same version); otherwise, it will be flagged as a duplicate.
     * @type {boolean}
     * @memberof PythonPackageUploadRequest
     */
    republish?: boolean;
    /**
     * A comma-separated values list of tags to add to the package.
     * @type {string}
     * @memberof PythonPackageUploadRequest
     */
    tags?: string | null;
}

/**
 * Check if a given object implements the PythonPackageUploadRequest interface.
 */
export function instanceOfPythonPackageUploadRequest(value: object): value is PythonPackageUploadRequest {
    if (!('package_file' in value) || value['package_file'] === undefined) return false;
    return true;
}

export function PythonPackageUploadRequestFromJSON(json: any): PythonPackageUploadRequest {
    return PythonPackageUploadRequestFromJSONTyped(json, false);
}

export function PythonPackageUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PythonPackageUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'package_file': json['package_file'],
        'republish': json['republish'] == null ? undefined : json['republish'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function PythonPackageUploadRequestToJSON(json: any): PythonPackageUploadRequest {
    return PythonPackageUploadRequestToJSONTyped(json, false);
}

export function PythonPackageUploadRequestToJSONTyped(value?: PythonPackageUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'package_file': value['package_file'],
        'republish': value['republish'],
        'tags': value['tags'],
    };
}

