/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepositoryX509RsaCertificate
 */
export interface RepositoryX509RsaCertificate {
    /**
     * If selected this is the active key for this repository.
     * @type {boolean}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly active?: boolean;
    /**
     * The issued certificate.
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate?: string | null;
    /**
     * Base64 encoded CA certificate chain.
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate_chain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate_chain_fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate_chain_fingerprint_short?: string;
    /**
     * The SHA-256 long identifier used
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate_fingerprint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly certificate_fingerprint_short?: string;
    /**
     * 
     * @type {Date}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly created_at?: Date;
    /**
     * If selected this is the default key for this repository.
     * @type {boolean}
     * @memberof RepositoryX509RsaCertificate
     */
    readonly _default?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RepositoryX509RsaCertificate
     */
    issuing_status?: RepositoryX509RsaCertificateIssuingStatusEnum;
}


/**
 * @export
 */
export const RepositoryX509RsaCertificateIssuingStatusEnum = {
    Certificate_is_pending_to_be_issued: 'Certificate is pending to be issued',
    Certificate_successfully_issued: 'Certificate successfully issued',
    Error_issuing_certificate: 'Error issuing certificate'
} as const;
export type RepositoryX509RsaCertificateIssuingStatusEnum = typeof RepositoryX509RsaCertificateIssuingStatusEnum[keyof typeof RepositoryX509RsaCertificateIssuingStatusEnum];


/**
 * Check if a given object implements the RepositoryX509RsaCertificate interface.
 */
export function instanceOfRepositoryX509RsaCertificate(value: object): value is RepositoryX509RsaCertificate {
    return true;
}

export function RepositoryX509RsaCertificateFromJSON(json: any): RepositoryX509RsaCertificate {
    return RepositoryX509RsaCertificateFromJSONTyped(json, false);
}

export function RepositoryX509RsaCertificateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryX509RsaCertificate {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'certificate_chain': json['certificate_chain'] == null ? undefined : json['certificate_chain'],
        'certificate_chain_fingerprint': json['certificate_chain_fingerprint'] == null ? undefined : json['certificate_chain_fingerprint'],
        'certificate_chain_fingerprint_short': json['certificate_chain_fingerprint_short'] == null ? undefined : json['certificate_chain_fingerprint_short'],
        'certificate_fingerprint': json['certificate_fingerprint'] == null ? undefined : json['certificate_fingerprint'],
        'certificate_fingerprint_short': json['certificate_fingerprint_short'] == null ? undefined : json['certificate_fingerprint_short'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        '_default': json['default'] == null ? undefined : json['default'],
        'issuing_status': json['issuing_status'] == null ? undefined : json['issuing_status'],
    };
}

export function RepositoryX509RsaCertificateToJSON(json: any): RepositoryX509RsaCertificate {
    return RepositoryX509RsaCertificateToJSONTyped(json, false);
}

export function RepositoryX509RsaCertificateToJSONTyped(value?: Omit<RepositoryX509RsaCertificate, 'active'|'certificate'|'certificate_chain'|'certificate_chain_fingerprint'|'certificate_chain_fingerprint_short'|'certificate_fingerprint'|'certificate_fingerprint_short'|'created_at'|'default'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuing_status': value['issuing_status'],
    };
}

