/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryPrivilegeDict } from './RepositoryPrivilegeDict';
import {
    RepositoryPrivilegeDictFromJSON,
    RepositoryPrivilegeDictFromJSONTyped,
    RepositoryPrivilegeDictToJSON,
    RepositoryPrivilegeDictToJSONTyped,
} from './RepositoryPrivilegeDict';

/**
 * 
 * @export
 * @interface RepositoryPrivilegeInput
 */
export interface RepositoryPrivilegeInput {
    /**
     * List of objects with explicit privileges to the repository.
     * @type {Array<RepositoryPrivilegeDict>}
     * @memberof RepositoryPrivilegeInput
     */
    privileges: Array<RepositoryPrivilegeDict>;
}

/**
 * Check if a given object implements the RepositoryPrivilegeInput interface.
 */
export function instanceOfRepositoryPrivilegeInput(value: object): value is RepositoryPrivilegeInput {
    if (!('privileges' in value) || value['privileges'] === undefined) return false;
    return true;
}

export function RepositoryPrivilegeInputFromJSON(json: any): RepositoryPrivilegeInput {
    return RepositoryPrivilegeInputFromJSONTyped(json, false);
}

export function RepositoryPrivilegeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryPrivilegeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'privileges': ((json['privileges'] as Array<any>).map(RepositoryPrivilegeDictFromJSON)),
    };
}

export function RepositoryPrivilegeInputToJSON(json: any): RepositoryPrivilegeInput {
    return RepositoryPrivilegeInputToJSONTyped(json, false);
}

export function RepositoryPrivilegeInputToJSONTyped(value?: RepositoryPrivilegeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'privileges': ((value['privileges'] as Array<any>).map(RepositoryPrivilegeDictToJSON)),
    };
}

