/* tslint:disable */
/* eslint-disable */
/**
 * Cloudsmith API (v1)
 * The API to the Cloudsmith Service
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageRaw
 */
export interface UsageRaw {
    /**
     * 
     * @type {number}
     * @memberof UsageRaw
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof UsageRaw
     */
    percentage?: string;
    /**
     * 
     * @type {number}
     * @memberof UsageRaw
     */
    used?: number;
}

/**
 * Check if a given object implements the UsageRaw interface.
 */
export function instanceOfUsageRaw(value: object): value is UsageRaw {
    return true;
}

export function UsageRawFromJSON(json: any): UsageRaw {
    return UsageRawFromJSONTyped(json, false);
}

export function UsageRawFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageRaw {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function UsageRawToJSON(json: any): UsageRaw {
    return UsageRawToJSONTyped(json, false);
}

export function UsageRawToJSONTyped(value?: UsageRaw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'percentage': value['percentage'],
        'used': value['used'],
    };
}

